`timescale 1ns / 1ps
//============================================================================
//  Macintosh II - Verilator Simulation Wrapper
//
//  Adapted from LBMacTwo.sv for simulation
//============================================================================

module emu
(
	input         clk_sys,
	input         reset,

	// PS2 keyboard/mouse
	input [10:0]  ps2_key,
	input [24:0]  ps2_mouse,

	// RTC timestamp
	input [32:0]  timestamp,

	// VGA output
	output [7:0]  VGA_R,
	output [7:0]  VGA_G,
	output [7:0]  VGA_B,
	output        VGA_HS,
	output        VGA_VS,
	output        VGA_HB,
	output        VGA_VB,
	output        CE_PIXEL,

	// Audio output
	output [15:0] AUDIO_L,
	output [15:0] AUDIO_R,

	// ROM/disk loading interface (ioctl)
	input         ioctl_download,
	input         ioctl_wr,
	input [24:0]  ioctl_addr,
	input [15:0]  ioctl_dout,
	input [7:0]   ioctl_index,
	output reg    ioctl_wait = 1'b0,

	// SCSI block device interface
	output [31:0] sd_lba[2],
	output [1:0]  sd_rd,
	output [1:0]  sd_wr,
	input  [1:0]  sd_ack,
	input  [7:0]  sd_buff_addr,
	input  [15:0] sd_buff_dout,
	output [15:0] sd_buff_din[2],
	input         sd_buff_wr,
	input  [1:0]  img_mounted,
	input  [63:0] img_size,

	// CPU debug outputs
	output [31:0] debug_pc,
	output [15:0] debug_opcode,
	output        debug_fetch_valid,
	output  [2:0] debug_fc,           // Function code (2=supv program, 1=supv data, etc)
	output        debug_write_valid,  // Write bus cycle completed
	output [31:0] debug_write_addr,   // Write address
	output [15:0] debug_write_data,   // Write data
	output        debug_cirrd_valid,  // FPU CIR read cycle completed (FC=7, $22000-$2203F)
	output [31:0] debug_cirrd_addr,   // CIR read address
	output [15:0] debug_cirrd_data,   // CIR read data (as seen by the CPU)

	// RAM debug outputs
	output [24:0] debug_ram_addr,
	output [15:0] debug_ram_din,
	output [15:0] debug_ram_dout,
	output        debug_ram_we,
	output        debug_ram_oe,
	output  [1:0] debug_ram_ds,
	output        debug_selectRAM,
	output        debug_selectROM,

	// Peripheral debug outputs
	output        debug_selectVIA,
	output        debug_selectNuBus,
	output        debug_selectSCSI,
	output        debug_selectSCC,
	output        debug_selectIWM,
	output        debug_selectASC,
	output        debug_memoryOverlayOn,
	output [31:0] debug_cpuAddr,
	output [15:0] debug_cpuDataIn,    // Data from CPU to peripherals
	output [15:0] debug_cpuDataOut,   // Data from peripherals to CPU
	output        debug_cpuRW,        // 1=read, 0=write
	output        debug_cpuBusControl,
	output        debug_viaRd,        // VIA read enable (VMA-synchronized)
	output        debug_viaWr,        // VIA write enable (VMA-synchronized)
	output        debug_cpuAS,        // CPU AS signal (active low)
	output        debug_cpuVMA,       // VMA signal (active low)
	output        debug_cpuVPA,       // VPA signal (active low)
	output        debug_cpuDTACK,     // DTACK signal (active low)
	output        debug_cpuUDS,       // UDS signal (active low)
	output        debug_cpuLDS,       // LDS signal (active low)
	output        debug_selectVIA2,
	output        debug_berr,
	output [31:0] debug_vbr,
	output  [2:0] debug_cpuIPL,

	// berr-rerun investigation (2026-07-12): format-$B RTE / berr_inhibit
	output        debug_berr_inhibit,   // TG68 rerun window active
	output [31:0] debug_berr_data,      // berr_data_buf re-fed during the window
	output        debug_busev_valid,    // one pulse per completed CPU bus cycle
	output [31:0] debug_busev_addr,
	output [15:0] debug_busev_data,     // word the CPU RECEIVED (reads) / drove (writes)
	output        debug_busev_rw,       // 1=read
	output  [2:0] debug_busev_fc,

	// Serial terminal interface
	output        serial_txd,       // SCC Channel A TX output (for sim-side RX)
	input         serial_rxd,       // SCC Channel A RX input (from sim-side TX)

	// Machine configuration inputs
	input  [1:0]  cfg_cpuType,      // 00=FX68K, 01/10/11=TG68K variants
	input  [1:0]  cfg_memSize       // RAM size: 00=1MB, 01=2MB, 10=4MB, 11=8MB
);

	localparam SCSI_DEVS = 2;

	// Configuration - directly from inputs (Mac II)
	wire [1:0] status_mem = cfg_memSize;     // RAM size (matches FPGA status[5:4])
	wire [1:0] status_cpu = cfg_cpuType;     // CPU type (must use TG68K 68030 mode)
	// Mac II: 31.3344 MHz system clock (2 × C15M), CPU at 15.6672 MHz via clk16_en.
	// Sim plusarg +cpu8 lets us test whether boot divergence is CPU/bus pacing.
	wire      status_turbo = !$test$plusargs("cpu8");
	////////////////////   CLOCKS   ///////////////////

	// Clock generation (clk_sys is 31.3344 MHz from testbench, matching FPGA PLL)
	wire clk_mem = clk_sys;  // Use same clock for memory
	wire pll_locked = !reset;

	// Clock enables - generated by addrController_top
	wire clk8_en_p, clk8_en_n;
	wire clk16_en_p, clk16_en_n;
	wire clk8;
	
	// Generate clk_sys enable (one tick per cycle at 31.3344 MHz)
	reg clk32_en_p, clk32_en_n;
	always @(posedge clk_sys) clk32_en_p <= 1'b1;
	always @(negedge clk_sys) clk32_en_n <= 1'b1;

	// Reset logic
	// NOTE: Do NOT include _cpuReset_o here! The RESET instruction drives
	// reset_n low to reset peripherals, but should NOT reset the CPU itself.
	// IMPORTANT: In simulation, wait for ROM download to complete before releasing reset
	reg n_reset = 0;
	reg n_reset_prev = 0;
	reg dio_download_prev = 0;
	always @(posedge clk_sys) begin
		reg [15:0] rst_cnt;

		if (clk8_en_p) begin
			n_reset_prev <= n_reset;
			dio_download_prev <= dio_download;

			// Debug: track when download completes
			if (dio_download_prev && !dio_download) begin
				$display("SIM: dio_download went LOW - ROM download complete");
			end

			if(~pll_locked || reset || dio_download) begin
				rst_cnt <= '1;
				n_reset <= 0;
			end
			else if(rst_cnt) begin
				rst_cnt <= rst_cnt - 1'd1;
				// Debug: show countdown progress every 0x1000 cycles
				if (rst_cnt[11:0] == 12'h000) begin
					$display("SIM: rst_cnt=%04x n_reset=%b", rst_cnt, n_reset);
				end
			end
			else begin
				n_reset <= 1;
			end

			// Debug: track when n_reset changes
			if (n_reset != n_reset_prev) begin
				$display("SIM: *** n_reset changed to %b *** (rst_cnt=%04x)", n_reset, rst_cnt);
			end
		end
	end

	///////////////////////////////////////////////////

	wire nubus_ce_pixel;
	assign CE_PIXEL  = nubus_ce_pixel;

	// Video Output - Mac II NuBus video system
	// nubus_blank is active-high DE (1 = visible pixels, 0 = blanked)
	// VGA_HB/VGA_VB need active-high blanking (1 = blanked), so invert
	assign VGA_R  = nubus_r;
	assign VGA_G  = nubus_g;
	assign VGA_B  = nubus_b;
	wire VGA_DE = nubus_blank;
	assign VGA_VS = nubus_vsync;
	assign VGA_HS = nubus_hsync;
	assign VGA_HB = ~nubus_blank;
	assign VGA_VB = ~nubus_blank;

	wire [15:0] asc_audio_l, asc_audio_r;
	assign AUDIO_L = asc_audio_l;
	assign AUDIO_R = asc_audio_r;

	// Mac II memory configuration
	localparam configROMSize = 2'b10;  // 256K ROM
	wire [1:0] configRAMSize = cfg_memSize; // RAM size from --ram (00=1MB,01=2MB,10=4MB,11=8MB)

	// Serial Ports — connected to serial terminal in sim_main.cpp
	wire serialOut;              // SCC Channel A TX (driven by SCC)
	wire serialIn = serial_rxd; // SCC Channel A RX (driven by sim)
	wire serialCTS = 1'b0;
	wire serialRTS;
	assign serial_txd = serialOut;

	// NuBus Video system wires
	wire [15:0] nubusDataOut_card;
	wire nubusAck_card;
	wire nubus_irq_n;

	// NuBus arbiter: handles empty-slot bus errors (see nubus_arbiter.sv)
	wire [15:0] nubusDataOut;
	wire nubusAck;
	wire nubus_acked_arb;
	wire nubus_berr;

	nubus_arbiter nubus_arb (
		.clk(clk_sys),
		._cpuAS(_cpuAS),
		.cpuAddr(cpuAddr),
		.selectNuBus(selectNuBus),
		.card_data_out(nubusDataOut_card),
		.card_ack_n(nubusAck_card),
		.data_out(nubusDataOut),
		.ack_n(nubusAck),
		.acked(nubus_acked_arb),
		.berr(nubus_berr)
	);
	wire [7:0] nubus_r, nubus_g, nubus_b;
	wire nubus_hsync, nubus_vsync, nubus_blank;
	wire selectNuBus;

	// interconnects
	// CPU
	wire _cpuReset, _cpuReset_o, _cpuUDS, _cpuLDS, _cpuRW, _cpuAS;
	wire _cpuVMA, _cpuVPA, _cpuDTACK;
	wire E_rising, E_falling;
	wire [2:0] _cpuIPL;
	wire [2:0] cpuFC;
	wire [7:0] cpuAddrHi;
	wire [31:0] cpuAddr;
	wire [15:0] cpuDataOut;

	// RAM/ROM
	wire _romOE;
	wire _ramOE, _ramWE;
	wire _memoryUDS, _memoryLDS;
	wire videoBusControl;
	wire dioBusControl;
	wire cpuBusControl;
	wire [22:0] memoryAddr;	// 23-bit byte address (8MB max RAM)
	wire [15:0] memoryDataOut;
	wire memoryLatch;
	wire capslock;
	
	// peripherals
	wire vid_alt, loadPixels, pixelOut, _hblank, _vblank, hsync, vsync;
	wire memoryOverlayOn, selectSCSI, selectSCSIDMA, scsiDREQ, selectSCC, selectIWM, selectVIA, selectVIA2, selectRAM, selectROM, selectSEOverlay, selectASC;
	wire [1:0] glueRAMSize;
	wire [15:0] dataControllerDataOut;

	// MC68881 FPU coprocessor cycles use FC=7 CPU space, cpID=1.
	// The Verilator harness uses a fast CIR-level responder for boot/debug runs.
	wire fpuAddrMatch = (cpuFC == 3'b111) && (cpuAddr[31:16] == 16'h0002) && (cpuAddr[15:13] == 3'b001);
	wire selectFPU = fpuAddrMatch && !_cpuAS;
	wire [31:0] fpu_data_out;
	wire fpu_dsack0_n, fpu_dsack1_n;
	wire fpu_sense_n;

	// floppy disk image interface
	wire dskReadAckInt;
	wire [21:0] dskReadAddrInt;
	wire dskReadAckExt;
	wire [21:0] dskReadAddrExt;

	// dtack generation in turbo mode
	reg  turbo_dtack_en, cpuBusControl_d;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			turbo_dtack_en <= 0;
		end
		else begin
			cpuBusControl_d <= cpuBusControl;
			if (_cpuAS) turbo_dtack_en <= 0;
			if (!_cpuAS & ((!cpuBusControl_d & cpuBusControl) | (!selectROM & !selectRAM))) turbo_dtack_en <= 1;
		end
	end

	// VPA: assert for FC=7 autovector cycles, except FPU coprocessor cycles.
	wire viaAccess = selectVIA | selectVIA2;
	assign      _cpuVPA = (cpuFC == 3'b111 && !selectFPU) ? 1'b0 :
	                      viaAccess ? ~!_cpuAS :
	                      ~(!_cpuAS && cpuAddr[23:21] == 3'b111);
	wire sim_ram_dtack = (~(!_cpuAS && cpuAddr[23:21] != 3'b111) | (status_turbo & !turbo_dtack_en));
	// DTACK: FPU uses DSACK; VIA accesses use VPA/VMA synchronous handshake.
	assign      _cpuDTACK = selectFPU ? (eff_fpu_dsack0_n & eff_fpu_dsack1_n) :
	                        selectNuBus ? nubusAck :
	                        selectSCSIDMA ? ~scsiDREQ :
	                        viaAccess ? 1'b1 :
	                        sim_ram_dtack;

	// Bus error timeout — undecoded addresses trigger bus error after ~8us
	reg [8:0] berr_counter;
	reg berr_out;
	wire nubus_acked = nubus_acked_arb;  // from nubus_arbiter: card or empty-slot responded
	wire scsi_dma_wait = selectSCSIDMA && !scsiDREQ;
	wire any_select = selectRAM | selectROM | selectVIA | selectVIA2 | selectSCC
	                | (selectSCSI && !scsi_dma_wait) | selectIWM | selectASC | nubus_acked | selectSEOverlay | selectFPU;
	wire is_cpu_space = (cpuFC == 3'b111);

	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			berr_counter <= 0;
			berr_out <= 0;
		end else begin
			if (_cpuAS) begin
				berr_counter <= 0;
				berr_out <= 0;
			end else if (berr_out) begin
				// Hold BERR until AS deasserts (CPU ends bus cycle)
			end else if (is_cpu_space || any_select)
				berr_counter <= 0;
			else if (berr_counter == 9'd251)  // ~8us at 31.3344 MHz sys clock
				begin berr_out <= 1; berr_counter <= 0; end
			else
				berr_counter <= berr_counter + 1'd1;
		end
	end
	// Mac II: C15M = 15.6672 MHz CPU (status_turbo=1 selects clk16_en from 31.3344 MHz sys clock)
	wire        cpu_en_p      = status_turbo ? clk16_en_p : clk8_en_p;
	wire        cpu_en_n      = status_turbo ? clk16_en_n : clk8_en_n;
	assign      _cpuReset_o   = tg68_reset_n;
	assign      _cpuRW        = tg68_rw;
	assign      _cpuAS        = tg68_as_n;
	assign      _cpuUDS       = tg68_uds_n;
	assign      _cpuLDS       = tg68_lds_n;
	assign      E_falling     = tg68_E_falling;
	assign      E_rising      = tg68_E_rising;
	assign      _cpuVMA       = tg68_vma_n;
	assign      cpuFC[0]      = tg68_fc0;
	assign      cpuFC[1]      = tg68_fc1;
	assign      cpuFC[2]      = tg68_fc2;
	// Mac II HMMU: translate CPU address when VIA2 PB3 is driven low.
	// FC=7 (CPU space / coprocessor CIR) bypasses translation.
	wire        hmmu_active;
	wire [31:0] cpuAddr_xlated;
	hmmu u_hmmu(.addr_in(tg68_a), .active(hmmu_active), .addr_out(cpuAddr_xlated));
	assign      cpuAddr       = (cpuFC == 3'b111) ? tg68_a : cpuAddr_xlated;
	assign      cpuDataOut    = tg68_dout;

	// tg68k wire declarations
	wire        tg68_rw;
	wire        tg68_as_n;
	wire        tg68_uds_n;
	wire        tg68_lds_n;
	wire        tg68_E_rising;
	wire        tg68_E_falling;
	wire        tg68_vma_n;
	wire        tg68_fc0;
	wire        tg68_fc1;
	wire        tg68_fc2;
	wire [15:0] tg68_dout;
	wire [31:0] tg68_a;
	wire        tg68_reset_n;
	wire        tg68_longword;

	tg68k tg68k_inst (
		.clk        ( clk_sys      ),
		.reset      ( !_cpuReset   ),
		.phi1       ( cpu_en_p     ),
		.phi2       ( cpu_en_n     ),
		.cpu        ( 2'b11        ), // 68020 mode (cpu(0) must be 1 for VBR support)

		.dtack_n    ( _cpuDTACK    ),
		.rw_n       ( tg68_rw      ),
		.as_n       ( tg68_as_n    ),
		.uds_n      ( tg68_uds_n   ),
		.lds_n      ( tg68_lds_n   ),
		.fc         ( { tg68_fc2, tg68_fc1, tg68_fc0 } ),
		.reset_n    ( tg68_reset_n ),

		.E          (              ),
		.E_div      ( status_turbo ),
		.E_PosClkEn ( tg68_E_falling ),
		.E_NegClkEn ( tg68_E_rising  ),
		.vma_n      ( tg68_vma_n   ),
		.vpa_n      ( _cpuVPA      ),

		.br_n       ( 1'b1         ),
		.bg_n       (              ),
		.bgack_n    ( 1'b1         ),

		.ipl        ( _cpuIPL      ),
		.berr       ( berr_effective ),
		.cpu_halted (              ),
		.din        ( cpu_data_in  ),
		.dout       ( tg68_dout    ),
		.longword   ( tg68_longword ),
		.addr       ( tg68_a       ),
		.VBR_out    ( debug_vbr    ),
		.berr_inhibit ( cpu_berr_inhibit ),
		.berr_data    ( cpu_berr_data    )
	);

	// Format $B RTE: when berr_inhibit is active, suppress bus errors
	// and provide the data input buffer value from the exception frame
	wire cpu_berr_inhibit;
	wire [31:0] cpu_berr_data;
	wire berr_effective = cpu_berr_inhibit ? 1'b0 : berr_out;
	reg [15:0] fpu_data_hold;
	reg fpu_data_hold_valid;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			fpu_data_hold <= 16'h0000;
			fpu_data_hold_valid <= 1'b0;
		end else if (!_cpuAS && selectFPU && _cpuRW) begin
			fpu_data_hold <= fpu_d_to_cpu;
			fpu_data_hold_valid <= 1'b1;
		end else if (!_cpuAS && !selectFPU) begin
			fpu_data_hold_valid <= 1'b0;
		end
	end

	wire [15:0] cpu_data_in = cpu_berr_inhibit ? cpu_berr_data[15:0] :
	                          selectFPU ? fpu_d_to_cpu :
	                          fpu_data_hold_valid ? fpu_data_hold :
	                          dataControllerDataOut;

	// CIR register address remapping (mirrors LBMacTwo.sv):
	//   Standard reg 0 (Response) -> mc68881_top reg 13
	//   Standard reg 2 (Save)     -> mc68881_top reg 12
	//   Standard reg 3 (Restore)  -> mc68881_top reg 28
	wire [4:0] fpu_addr_remapped = (cpuAddr[5:1] == 5'd0) ? 5'd13 :
	                               (cpuAddr[5:1] == 5'd2) ? 5'd12 :
	                               (cpuAddr[5:1] == 5'd3) ? 5'd28 :
	                               cpuAddr[5:1];

	// -------------------- 16-bit ↔ 32-bit FPU bus adapter -----------------
	// Ported from SingleStepTests/cpu_fpu/cpu_fpu_tests.v. TG68K has a
	// 16-bit data bus and splits .L into 2 word transfers; mc68881_top's
	// Operand CIR is a 32-bit register and expects ONE transfer per
	// long-word (per AN-947 / M68020 PRM §9):
	//   - WRITES (CPU→FPU): latch the first 16-bit half into fpu_wr_hi.
	//     Suppress cs_n on the first half (FPU sees nothing) and fake a
	//     DSACK back to TG68K. On the second half, drive
	//     d_in = {fpu_wr_hi, cpuDataOut} as a single 32-bit transfer and
	//     let the FPU's DSACK pass through.
	//   - READS (FPU→CPU): on the first half, let the FPU strobe normally
	//     and latch the full 32-bit d_out into fpu_rd_latch. TG68K gets
	//     the HIGH word. On the second half, suppress cs_n (FPU doesn't
	//     advance), fake DSACK, return the LOW half from the latch.
	// Non-Operand CIR accesses pass through unchanged (16-bit semantics).
	wire fpu_is_operand_cycle = (fpu_addr_remapped == 5'd8);
	reg        fpu_xfer_phase;   // 0 = first half (HIGH), 1 = second half (LOW)
	reg [15:0] fpu_wr_hi;
	reg [31:0] fpu_rd_latch;
	reg        fpu_prev_as_for_phase;
	// Flip phase on the END of each FPU operand bus cycle (AS-rising edge
	// while addressed at operand) so phase is stable throughout each cycle.
	wire fpu_bus_end_edge = fpuAddrMatch && fpu_is_operand_cycle
	                        && _cpuAS && !fpu_prev_as_for_phase;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			fpu_xfer_phase        <= 1'b0;
			fpu_wr_hi             <= 16'h0000;
			fpu_rd_latch          <= 32'h0000_0000;
			fpu_prev_as_for_phase <= 1'b1;
		end else begin
			fpu_prev_as_for_phase <= _cpuAS;
			// Capture at the END of each access (AS-rising edge), when the
			// FPU has just dsacked and data is valid. Latches simultaneously
			// with the phase flip.
			if (fpu_bus_end_edge && fpu_xfer_phase == 1'b0) begin
				if (!_cpuRW) fpu_wr_hi    <= cpuDataOut;
				else         fpu_rd_latch <= fpu_data_out;
			end
			if (fpu_bus_end_edge)
				fpu_xfer_phase <= ~fpu_xfer_phase;
		end
	end

	// WRITES: FPU active on phase=1 (second half); READS: active on phase=0.
	wire fpu_active_phase = _cpuRW ? !fpu_xfer_phase : fpu_xfer_phase;
	wire fpu_cs_n_eff = fpu_is_operand_cycle
	                    ? ~(fpuAddrMatch && fpu_active_phase)
	                    : ~fpuAddrMatch;
	wire [31:0] fpu_d_in_eff = (fpu_is_operand_cycle && !_cpuRW)
	                           ? {fpu_wr_hi, cpuDataOut}
	                           : {16'h0000, cpuDataOut};
	// TG68K-side DSACK: fake during the inactive phase, pass-through during
	// the active phase.
	wire fpu_inactive_phase_act = fpuAddrMatch && fpu_is_operand_cycle
	                              && !_cpuAS && !fpu_active_phase;
	wire eff_fpu_dsack0_n = fpu_inactive_phase_act ? 1'b0 : fpu_dsack0_n;
	wire eff_fpu_dsack1_n = fpu_inactive_phase_act ? 1'b1 : fpu_dsack1_n;
	// TG68K read mux:
	//  - Non-Operand: FPU's d_out[15:0] (16-bit response/save/etc).
	//  - Operand phase=0: HIGH word direct from FPU's d_out[31:16].
	//  - Operand phase=1: LOW word from the latch.
	wire [15:0] fpu_d_to_cpu = fpu_is_operand_cycle
	                           ? (fpu_xfer_phase ? fpu_rd_latch[15:0]
	                                             : fpu_data_out[31:16])
	                           : fpu_data_out[15:0];
	// Size encoding: derive from longword + UDS/LDS.
	wire [1:0] fpu_size_n =
	    _cpuAS                     ? 2'b11 :  // idle
	    tg68_longword              ? 2'b00 :  // .L
	    (!_cpuUDS && !_cpuLDS)     ? 2'b10 :  // .W
	                                 2'b01;   // .B

`ifdef USE_FPU_STUB
	// CIR-protocol no-op stub (Makefile: USE_FPU_STUB=1). Accepts writes,
	// always returns "done". Doesn't compute anything; useful when running
	// non-FPU software and skipping FPU area/runtime cost.
	sim_fpu_cir_stub fpu_inst (
		.clk          ( clk_sys              ),
		.reset_n      ( _cpuReset            ),
		.a_in         ( cpuAddr[5:1]         ),  // stub doesn't need remap
		.d_in         ( fpu_d_in_eff         ),
		.d_out        ( fpu_data_out         ),
		.size_n       ( fpu_size_n           ),
		.as_n         ( _cpuAS               ),
		.cs_n         ( fpu_cs_n_eff         ),
		.rw           ( _cpuRW               ),
		.ds_n         ( _cpuUDS & _cpuLDS    ),
		.dsack0_n     ( fpu_dsack0_n         ),
		.dsack1_n     ( fpu_dsack1_n         ),
		.sense_n      ( fpu_sense_n          ),
		.status_valid (                      )
	);
`else
	// Real MC68881 (lite variant — same FPU instantiated in production
	// LBMacTwo.sv). Default for this sim so functional FPU behavior is
	// tested. Has the B-4 F-line trap fix for unsupported ops.
	mc68881_top fpu_inst (
		.clk          ( clk_sys              ),
		.reset_n      ( _cpuReset            ),
		.a_in         ( fpu_addr_remapped    ),
		.d_in         ( fpu_d_in_eff         ),
		.d_out        ( fpu_data_out         ),
		.size_n       ( fpu_size_n           ),
		.as_n         ( _cpuAS               ),
		.cs_n         ( fpu_cs_n_eff         ),
		.rw           ( _cpuRW               ),
		.ds_n         ( _cpuUDS & _cpuLDS    ),
		.dsack0_n     ( fpu_dsack0_n         ),
		.dsack1_n     ( fpu_dsack1_n         ),
		.sense_n      ( fpu_sense_n          ),
		.status_valid (                      )
	);
`endif
	
	// CPU debug - simplified without busstate
	reg [31:0] last_fetch_pc;
	reg [15:0] last_fetch_opcode;
	reg        fetch_valid;
	reg  [2:0] last_fetch_fc;
	reg        prev_as_n;

	// Write capture for vector table watchpoint
	reg        write_valid;
	reg [31:0] write_addr;
	reg [15:0] write_data;

	// FPU CIR read capture (FSAVE frame / response reads are otherwise invisible)
	reg        cirrd_valid;
	reg [31:0] cirrd_addr;
	reg [15:0] cirrd_data;

	// Capture VIA read data while AS is still asserted
	reg [15:0] via_rd_data_r;
	always @(posedge clk_sys) begin
		if (!tg68_as_n && selectVIA && tg68_rw)
			via_rd_data_r <= dataControllerDataOut;
	end

	always @(posedge clk_sys) begin
		if (!n_reset) begin
			fetch_valid <= 0;
			write_valid <= 0;
			prev_as_n <= 1;
			last_fetch_pc <= 0;
			last_fetch_opcode <= 0;
			last_fetch_fc <= 0;
		end else begin
			fetch_valid <= 0;
			write_valid <= 0;
			cirrd_valid <= 0;
			prev_as_n <= tg68_as_n;

			// Capture on AS rising edge (bus cycle complete)
			if (!prev_as_n && tg68_as_n) begin
				if (tg68_rw && (cpuFC == 3'b010 || cpuFC == 3'b110)) begin
					// Only capture instruction fetches (FC=2 supv program, FC=6 user program)
					last_fetch_pc <= tg68_a;
					last_fetch_opcode <= dataControllerDataOut;
					last_fetch_fc <= cpuFC;
					fetch_valid <= 1;
				end else if (!tg68_rw) begin
					// Write cycle - capture for vector watchpoint
					write_addr <= tg68_a;
					write_data <= tg68_dout[15:0];
					write_valid <= 1;
				end else if (tg68_rw && cpuFC == 3'b111 &&
				             tg68_a[31:16] == 16'h0002 && tg68_a[15:6] == 10'h080) begin
					// FPU CIR read ($22000-$2203F): log what the CPU saw
					cirrd_addr <= tg68_a;
					cirrd_data <= fpu_d_to_cpu;
					cirrd_valid <= 1;
				end
				// Uncomment for VIA bus read debugging:
				// if (tg68_rw && tg68_a[31:20] == 12'h50F)
				//	$display("VIA_BUS_RD_LATE: addr=%h data=%h via_din_r=%h UDS=%b LDS=%b selVIA=%b",
				//		tg68_a, dataControllerDataOut, via_rd_data_r, _cpuUDS, _cpuLDS, selectVIA);
			end
		end
	end

	assign debug_pc = last_fetch_pc;
	assign debug_opcode = last_fetch_opcode;
	assign debug_fetch_valid = fetch_valid;
	assign debug_fc = last_fetch_fc;
	assign debug_write_valid = write_valid;
	assign debug_write_addr = write_addr;
	assign debug_write_data = write_data;
	assign debug_cirrd_valid = cirrd_valid;
	assign debug_cirrd_addr = cirrd_addr;
	assign debug_cirrd_data = cirrd_data;
	assign debug_berr = berr_out;

	// --- berr-rerun investigation (2026-07-12) -------------------------------
	// One event per completed CPU bus cycle, carrying the word the CPU actually
	// RECEIVED (cpu_data_in — which is berr_data_buf during a berr_inhibit rerun
	// window; debug_opcode logs dataControllerDataOut and would hide that).
	reg        busev_valid_r;
	reg [31:0] busev_addr_r, busev_addr_l;
	reg [15:0] busev_data_r, busev_data_l;
	reg        busev_rw_r, busev_rw_l;
	reg [2:0]  busev_fc_r, busev_fc_l;
	reg        busev_as_d = 1'b1;
	always @(posedge clk_sys) begin
		busev_valid_r <= 0;
		busev_as_d <= tg68_as_n;
		if (!tg68_as_n) begin
			busev_addr_l <= tg68_a;
			busev_data_l <= tg68_rw ? cpu_data_in : tg68_dout[15:0];
			busev_rw_l   <= tg68_rw;
			busev_fc_l   <= cpuFC;
		end
		if (!busev_as_d && tg68_as_n) begin
			busev_addr_r  <= busev_addr_l;
			busev_data_r  <= busev_data_l;
			busev_rw_r    <= busev_rw_l;
			busev_fc_r    <= busev_fc_l;
			busev_valid_r <= 1;
		end
	end
	assign debug_busev_valid  = busev_valid_r;
	assign debug_busev_addr   = busev_addr_r;
	assign debug_busev_data   = busev_data_r;
	assign debug_busev_rw     = busev_rw_r;
	assign debug_busev_fc     = busev_fc_r;
	assign debug_berr_inhibit = cpu_berr_inhibit;
	assign debug_berr_data    = cpu_berr_data;

	addrController_top ac0
	(
		.clk(clk_sys),
		.clk8(clk8),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.clk16_en_p(clk16_en_p),
		.clk16_en_n(clk16_en_n),
		.cpuAddr(cpuAddr),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuAS(_cpuAS),
		.turbo(status_turbo),
		.configROMSize(configROMSize),
		.configRAMSize(configRAMSize),
		.glueRAMSize(glueRAMSize),
		.memoryAddr(memoryAddr),
		.memoryLatch(memoryLatch),
		._memoryUDS(_memoryUDS),
		._memoryLDS(_memoryLDS),
		._romOE(_romOE),
		._ramOE(_ramOE),
		._ramWE(_ramWE),
		.videoBusControl(videoBusControl),
		.dioBusControl(dioBusControl),
		.cpuBusControl(cpuBusControl),
		.selectSCSI(selectSCSI),
		.selectSCSIDMA(selectSCSIDMA),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectVIA2(selectVIA2),
		.selectRAM(selectRAM),
		.selectROM(selectROM),
		.selectSEOverlay(selectSEOverlay),
		.selectNuBus(selectNuBus),
		.selectASC(selectASC),
		.hsync(hsync),
		.vsync(vsync),
		._hblank(_hblank),
		._vblank(_vblank),
		.loadPixels(loadPixels),
		.vid_alt(vid_alt),
		.memoryOverlayOn(memoryOverlayOn),

		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt)
	);

	wire [1:0] diskEject;
	wire [1:0] diskMotor, diskAct;

	// NuBus Video Card — Mac II High-Resolution (TFB 2.2 + Bt453)
	// VRAM: use the real dual-port on-chip BRAM (vram_ram) so sim matches
	// hardware.  Port A = CPU read/write (card FSM); Port B = video scanout.
	// (Previously sim used a single-port sim_vram and never wired Port B, so
	// the scanout read undriven 0 -> black screen.)
	wire [24:0] sim_vram_addr;
	wire [15:0] sim_vram_dout;
	wire [15:0] sim_vram_din;
	wire        sim_vram_rd;
	wire        sim_vram_wr;
	wire        sim_vram_ready;

	wire [24:0] sim_vram_scan_addr;
	wire        sim_vram_scan_rd;
	wire [15:0] sim_vram_scan_data;

	vram_ram #(.WORDS(196608)) sim_vram_inst (   // 384 KB (matches hardware)
		.clk    (clk_sys),
		// Port A — CPU read/write (card FSM)
		.addr   (sim_vram_addr),
		.din    (sim_vram_dout),
		.dout   (sim_vram_din),
		.rd     (sim_vram_rd),
		.wr     (sim_vram_wr),
		.ready  (sim_vram_ready),
		// Port B — dedicated scanout read
		.addr_b (sim_vram_scan_addr),
		.rd_b   (sim_vram_scan_rd),
		.dout_b (sim_vram_scan_data)
	);

	nubus_video_mdc824 nubus_card (
		.clk(clk_sys),
		.reset(!_cpuReset),
		.addr(cpuAddr),
		.data_in(cpuDataOut),
		.data_out(nubusDataOut_card),
		.uds_lds({!_cpuUDS, !_cpuLDS}),
		.cpu_longword(tg68_longword),
		.rw_n(_cpuRW),
		.cpu_as_n(_cpuAS),
		.select(selectNuBus),
		.ack_n(nubusAck_card),
		.vga_r(nubus_r),
		.vga_g(nubus_g),
		.vga_b(nubus_b),
		.vga_hs(nubus_hsync),
		.vga_vs(nubus_vsync),
		.vga_blank(nubus_blank),
		.vga_clk(),
		.ce_pixel(nubus_ce_pixel),
		.nmrq_n(nubus_irq_n),

		.vram_addr(sim_vram_addr),
		.vram_dout(sim_vram_dout),
		.vram_din(sim_vram_din),
		.vram_rd(sim_vram_rd),
		.vram_wr(sim_vram_wr),
		.vram_ready(sim_vram_ready),

		.vram_scan_addr(sim_vram_scan_addr),
		.vram_scan_rd(sim_vram_scan_rd),
		.vram_scan_data(sim_vram_scan_data),

		.overlay_en(1'b0),
		.monochrome(1'b0),
		.monitor_512(1'b0),   // sim always models the 640x480 13" monitor

		.ioctl_wr(ioctl_wr),
		.ioctl_addr(ioctl_addr),
		.ioctl_data(ioctl_dout),
		.ioctl_download(ioctl_download),
		.ioctl_index(ioctl_index)
	);

	dataController_top #(SCSI_DEVS) dc0
	(
		.clk32(clk_sys),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.clk16_en_p(clk16_en_p),
		.clk16_en_n(clk16_en_n),
		.E_rising(E_rising),
		.E_falling(E_falling),
		.machineType(1'b1),  // Mac II mode
		.macModel(3'd2),     // Mac II (non-FDHD)
		.configRAMSize(configRAMSize),
		._systemReset(n_reset),
		._cpuReset(_cpuReset),
		._cpuIPL(_cpuIPL),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		.cpuLongword(tg68_longword),
		._cpuVMA(_cpuVMA),
		.selectNuBus(selectNuBus),
		.nubusDataIn(nubusDataOut),
		.nubus_irq_n(nubus_irq_n),
		.cpuDataIn(cpuDataOut),
		.cpuDataOut(dataControllerDataOut),
		.cpuAddrRegHi(cpuAddr[12:9]),
		.cpuAddrRegMid(cpuAddr[6:4]),
		.cpuAddrRegLo(cpuAddr[2:1]),
		.selectSCSI(selectSCSI),
		.selectSCSIDMA(selectSCSIDMA),
		.scsiDREQ(scsiDREQ),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectVIA2(selectVIA2),
		.selectSEOverlay(selectSEOverlay),
		.selectASC(selectASC),
		.cpuAddrASC(cpuAddr[12:0]),
		.cpuBusControl(cpuBusControl),
		.videoBusControl(videoBusControl),
		.memoryDataOut(memoryDataOut),
		.memoryDataIn(ram_do),
		.memoryLatch(memoryLatch),
		// SDRAM-coherency-fix slot handshake (fefc429, 2026-06-13): the
		// dataController read-delivery gate is now
		//   cpuSlotOwned && memoryLatch && cpu_rd_take
		// (was cpuBusControl && memoryLatch). sim.v was never updated when
		// those two inputs were added, so with -Wno-PINMISSING they floated to
		// 0 and NO ROM/RAM read data ever reached the CPU — the CPU booted into
		// zeroed memory and wandered. sim_ram is combinational and always
		// returns the addressed word (no arbiter, no neighbor-slot hazard), so
		// reproduce the old gate exactly: own the slot whenever the CPU has bus
		// control, and always take the read (no coherency mismatch to guard).
		.cpuSlotOwned(cpuBusControl),
		.cpu_rd_take(1'b1),

		.ps2_key(ps2_key),
		.capslock(capslock),
		.ps2_mouse(ps2_mouse),
		.serialIn(serialIn),
		.serialOut(serialOut),
		.serialCTS(serialCTS),
		.serialRTS(serialRTS),

		.timestamp(timestamp),

		// PRAM persistence: no HPS NVRAM image in sim — tie off
		.pram_load_wr(1'b0),
		.pram_load_addr(8'd0),
		.pram_load_data(8'd0),
		.pram_save_addr(8'd0),
		.pram_save_data(),
		.pram_wr_stb(),

		._hblank(_hblank),
		._vblank(_vblank),
		.pixelOut(pixelOut),
		.loadPixels(loadPixels),
		.vid_alt(vid_alt),

		.memoryOverlayOn(memoryOverlayOn),
		.glueRAMSize(glueRAMSize),
		.hmmu_active(hmmu_active),

		.ascAudioLeft(asc_audio_l),
		.ascAudioRight(asc_audio_r),

		.insertDisk({dsk_ext_ins, dsk_int_ins}),
		.diskSides({dsk_ext_ds, dsk_int_ds}),
		.diskMFM({dsk_ext_mfm, dsk_int_mfm}),
		.diskHD({dsk_ext_hd, dsk_int_hd}),
		.diskEject(diskEject),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.diskMotor(diskMotor),
		.diskAct(diskAct),

		.img_mounted(img_mounted),
		.img_size(img_size[40:9]),
		.io_lba(sd_lba),
		.io_rd(sd_rd),
		.io_wr(sd_wr),
		.io_ack(sd_ack),

		.sd_buff_addr(sd_buff_addr),
		.sd_buff_dout(sd_buff_dout),
		.sd_buff_din(sd_buff_din),
		.sd_buff_wr(sd_buff_wr)
	);

	//////////////////////// DOWNLOADING ///////////////////////////

	wire dio_download = ioctl_download;
	wire [23:0] dio_addr = ioctl_addr[24:1];
	wire [7:0] dio_index = ioctl_index;

	// Floppy disk image tracking
	reg dsk_int_ds, dsk_ext_ds;
	reg dsk_int_ss, dsk_ext_ss;
	reg dsk_int_mfm = 0, dsk_ext_mfm = 0;   // SWIM: MFM image mounted
	reg dsk_int_hd  = 0, dsk_ext_hd  = 0;   // SWIM: 1.44MB image mounted
	wire dsk_int_ins = dsk_int_ds || dsk_int_ss;
	wire dsk_ext_ins = dsk_ext_ds || dsk_ext_ss;

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 2) begin
			dsk_int_ds <= (dio_addr >= 409599 && dio_addr <= 409600);
			dsk_int_ss <= (dio_addr >= 204799 && dio_addr <= 204800);
			dsk_int_mfm <= (dio_addr >= 368639 && dio_addr <= 368640) || (dio_addr >= 737279 && dio_addr <= 737280);
			dsk_int_hd  <= (dio_addr >= 737279 && dio_addr <= 737280);
		end
		if(diskEject[0]) begin
			dsk_int_ds <= 0;
			dsk_int_ss <= 0;
		end
	end

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 3) begin
			dsk_ext_ds <= (dio_addr >= 409599 && dio_addr <= 409600);
			dsk_ext_ss <= (dio_addr >= 204799 && dio_addr <= 204800);
			dsk_ext_mfm <= (dio_addr >= 368639 && dio_addr <= 368640) || (dio_addr >= 737279 && dio_addr <= 737280);
			dsk_ext_hd  <= (dio_addr >= 737279 && dio_addr <= 737280);
		end
		if(diskEject[1]) begin
			dsk_ext_ds <= 0;
			dsk_ext_ss <= 0;
		end
	end

	reg [20:0] dio_a;
	reg [15:0] dio_data;
	reg        dio_write;
	reg        dio_old_cyc = 0;

	always @(posedge clk_sys) begin
		if(ioctl_wr) begin
			// Don't byte-swap for sim_ram (original swaps for SDRAM byte ordering)
			dio_data <= ioctl_dout;
			// Mac II ROM (boot0.rom, 256K = 128K words) starts at 0x40_0000 in address space
			// In sim_ram, ROM area is at bit[21]=1, so ROM goes to 0x200000+ in sim_ram
			// Floppy disk images use indices 2 and 3, but the storage
			// slots are word offsets 0x80000 and 0x100000.
			if (dio_index == 8'd0)
				dio_a <= {4'b0000, dio_addr[16:0]};  // ROM: 256K = 128K words
			else if (dio_index == 8'd1)
				dio_a <= {2'b11, dio_addr[18:0]};    // NuBus ROM is consumed directly
			else if (dio_index[1:0] == 2'd2 || dio_index[1:0] == 2'd3)
				dio_a <= {(dio_index[1:0] - 2'd1), dio_addr[19:0]};  // 1M-word floppy windows (1.44MB fits)
			else
				dio_a <= {dio_index[6], dio_addr[19:0]};
			ioctl_wait <= 1;
		end

		dio_old_cyc <= dioBusControl;
		if(~dioBusControl) dio_write <= ioctl_wait;
		if(dio_old_cyc & ~dioBusControl & dio_write) ioctl_wait <= 0;
	end

	////////////////////////// RAM /////////////////////////////////

	// Original download_cycle used dioBusControl handshake (for SDRAM timing)
	// wire download_cycle = dio_download && dioBusControl;

	// For simulation with synchronous RAM, use simplified direct download path
	// This bypasses the multi-cycle handshake latency from dioBusControl
	wire download_cycle = dio_download && ioctl_wr;

	// Combinational version of dio_a for download (avoids register latency)
	// Mac II ROM (boot0.rom, 256K) starts at 0x40_0000 in address space
	// ROM is 256K = 128K words, using dio_addr[16:0] (17 bits)
	// Floppy disk images at word offsets 0x100000 and 0x200000 (1M-word windows:
	// a 1.44MB image is 737,280 words and overflowed the old 512K-word slots).
	wire [21:0] dio_a_floppy = {(dio_index[1:0] - 2'd1), dio_addr[19:0]};
	wire [21:0] dio_a_comb = (dio_index == 8'd0) ? {5'b00000, dio_addr[16:0]} :
	                         (dio_index == 8'd1) ? {3'b011, dio_addr[18:0]} :
	                         ((dio_index[1:0] == 2'd2 || dio_index[1:0] == 2'd3) ? dio_a_floppy :
	                          {1'b0, dio_index[6], dio_addr[19:0]});

	// Address mapping for sim_ram (matches the FPGA SDRAM map, 8MB-capable):
	//   RAM        : 0x000000 - 0x3FFFFF (A22=0)  — up to 4M words = 8MB
	//   ROM / disk : 0x400000 +          (A22=1)  — moved above the 8MB RAM
	//                                               window so it no longer
	//                                               collides (it used to sit at
	//                                               A21=0x200000, inside 8MB RAM).
	wire [24:0] ram_addr = download_cycle ? {2'b00, 1'b1, dio_a_comb[21:0] } :   // ROM/disk download @ 0x400000+
						   ~_romOE        ? {2'b00, 1'b1, 5'b00000, memoryAddr[17:1]} : // ROM reads @ 0x400000+ (256K ROM)
						   (dskReadAckInt || dskReadAckExt) ? {2'b00, 1'b1, memoryAddr[22:1]} : // disk image @ 0x400000+
										  {3'b000, memoryAddr[22:1]};                  // RAM 0x000000-0x3FFFFF (8MB)
	// Use ioctl_dout directly for download (bypass registered dio_data)
	wire [15:0] ram_din  = download_cycle ? ioctl_dout            : memoryDataOut;
	wire  [1:0] ram_ds   = download_cycle ? 2'b11                 : { !_memoryUDS, !_memoryLDS };
	// Use ioctl_wr directly as write enable during download (bypass registered dio_write)
	wire        ram_we   = download_cycle ? 1'b1                  : !_ramWE;
	wire        ram_oe   = download_cycle ? 1'b0                  : (!_ramOE || !_romOE || dskReadAckInt || dskReadAckExt);
	wire [15:0] ram_do_raw;
	// Odd-addressed full-word reads (TG68's misaligned-transfer middle piece:
	// memoryAddr[0]=1 with BOTH strobes) must return the CONTAINING word raw —
	// the kernel does its own byte-lane extraction. This is the semantics the
	// SingleStepTests cpu_fpu bench provides (ram_read16 masks A0) and passes
	// with. A former "straddle" mux here ({byte@A, byte@A+1}) double-shifted
	// misaligned reads: a misaligned move.l source read returned {b0,b2,b3,b3}
	// and every misaligned BlockMove corrupted its destination (the System
	// resource map's DSAT ids read 0x00FF/0x02FF -> GetResource NIL -> boot-time
	// SysError(40) -> Sad Mac 0F/0028). Sim-harness bug only: the real top's
	// SDRAM path is word-addressed and naturally serves the containing word.
	wire [15:0] ram_do   = download_cycle ? 16'hffff :
	                       (dskReadAckInt || dskReadAckExt) ? extra_rom_data_demux :
	                       ram_do_raw;
	wire [15:0] extra_rom_data_demux = memoryAddr[0] ?
						   {ram_do_raw[7:0],ram_do_raw[7:0]}:{ram_do_raw[15:8],ram_do_raw[15:8]};

	sim_ram ram
	(
		.clk            ( clk_sys     ),
		.reset          ( reset       ),
		.din            ( ram_din     ),
		.addr           ( ram_addr    ),
		.ds             ( ram_ds      ),
		.we             ( ram_we      ),
		.oe             ( ram_oe      ),
		.dout           ( ram_do_raw  ),
		.debug_pc       ( last_fetch_pc )
	);

	// ── Reset-fetch tracer (why does the CPU boot into zeroed RAM?) ──────────
	// Print the first N CPU bus cycles so the boot overlay + ROM-select decode
	// and the resulting sim_ram address/data are visible. Enable with
	// +resetfetch_debug. Fires on the real cpuBusControl grant (not idle AS=0
	// samples). If overlay/selectROM are right but ram_do reads 0, the ROM
	// isn't in sim_ram; if selectROM never asserts, the overlay decode input
	// (memoryOverlayOn / configROMSize) is wrong.
	integer rf_dbg_cnt = 0;
	reg rf_bc_d = 1'b0;
	always @(posedge clk_sys) begin
		rf_bc_d <= cpuBusControl;
		if ($test$plusargs("resetfetch_debug") && rf_dbg_cnt < 80 &&
		    cpuBusControl && !_cpuAS && !dio_download) begin
			$display("RF[%0d] cpuAddr=%08h memAddr=%06h selROM=%b selRAM=%b ovl=%b _romOE=%b _ramOE=%b ram_addr=%07h ram_do=%04h rw=%b cfgROM=%b cfgRAM=%b",
				rf_dbg_cnt, cpuAddr, memoryAddr, selectROM, selectRAM, memoryOverlayOn,
				_romOE, _ramOE, ram_addr, ram_do, _cpuRW, configROMSize, configRAMSize);
			rf_dbg_cnt <= rf_dbg_cnt + 1;
		end
	end

	// Misaligned-write forensics (2026-07-16): per-clock view of a CPU write
	// cycle at BOTH interfaces (CPU emission vs sim_ram reception) inside the
	// resource-map copy destination window. Enable with +misalign_debug.
	// synthesis translate_off
	always @(posedge clk_sys) begin
		if ($test$plusargs("misalign_debug") && !tg68_as_n && !tg68_rw &&
		    tg68_a[23:0] >= 24'h012E00 && tg68_a[23:0] <= 24'h012F60)
			$display("MISW t=%0t a=%06x u=%b l=%b dout=%04x | mm=%06b odd=%b st=%b%b | dtack=%b",
			         $time, tg68_a[23:0], _cpuUDS, _cpuLDS, tg68_dout[15:0],
			         tg68k_inst.tg68k.memmask,
			         tg68k_inst.tg68k.oddout, tg68k_inst.tg68k.state[1], tg68k_inst.tg68k.state[0],
			         _cpuDTACK);
	end
	// synthesis translate_on

	// RAM debug outputs
	assign debug_ram_addr = ram_addr;
	assign debug_ram_din = ram_din;
	assign debug_ram_dout = ram_do_raw;
	assign debug_ram_we = ram_we;
	assign debug_ram_oe = ram_oe;
	assign debug_ram_ds = ram_ds;
	assign debug_selectRAM = selectRAM;
	assign debug_selectROM = selectROM;

	// Peripheral debug outputs
	assign debug_selectVIA = selectVIA;
	assign debug_selectNuBus = selectNuBus;
	assign debug_selectSCSI = selectSCSI;
	assign debug_selectSCC = selectSCC;
	assign debug_selectIWM = selectIWM;
	assign debug_selectASC = selectASC;
	assign debug_memoryOverlayOn = memoryOverlayOn;
	assign debug_cpuAddr = cpuAddr;  // Full 32-bit address for Mac II
	assign debug_cpuDataIn = cpuDataOut;  // CPU writes this to peripherals
	assign debug_cpuDataOut = dataControllerDataOut;  // Peripherals send this to CPU
	assign debug_cpuRW = _cpuRW;  // 1=read, 0=write
	assign debug_cpuBusControl = cpuBusControl;
	assign debug_viaRd = (selectVIA || selectVIA2) && !_cpuVMA && _cpuRW;
	assign debug_viaWr = (selectVIA || selectVIA2) && !_cpuVMA && !_cpuRW;
	assign debug_cpuAS = _cpuAS;
	assign debug_cpuVMA = _cpuVMA;
	assign debug_cpuVPA = _cpuVPA;
	assign debug_cpuDTACK = _cpuDTACK;
	assign debug_cpuUDS = _cpuUDS;
	assign debug_cpuLDS = _cpuLDS;
	assign debug_selectVIA2 = selectVIA2;
	assign debug_cpuIPL = _cpuIPL;

`ifdef SIMULATION
	integer lowmem_bit_raw_dbg_hits = 0;
	integer lowmem_bset_raw_window = 0;
	integer lowmem_bset_raw_hits = 0;
	always @(posedge clk_sys) begin
		if ($test$plusargs("lowmem_bset_raw_debug") && lowmem_bset_raw_hits < 96) begin
			if (last_fetch_pc >= 32'h4080DC84 && last_fetch_pc <= 32'h4080DC90)
				lowmem_bset_raw_window <= 48;
			else if (lowmem_bset_raw_window != 0)
				lowmem_bset_raw_window <= lowmem_bset_raw_window - 1;

			if (lowmem_bset_raw_window != 0 ||
			    (last_fetch_pc >= 32'h4080DC84 && last_fetch_pc <= 32'h4080DC90)) begin
				$display("LOWMEM_BSET_RAW[%0d] pc=%08h op=%04h k_op=%04h k_exe=%04h k_snd=%04h ms=%0d nms=%0d dec=%b exec=%b setexec=%b np=%b setnp=%b wb=%b ewb=%b eabn=%b set_eab=%b exe_eab=%b set_2nd=%b exe_2nd=%b set_bits=%b exe_bits=%b set_eaop1=%b exe_eaop1=%b phi1=%b phi2=%b core_state=%b wrap_state=%0d core_rw=%b core_addr=%08h core_dout=%04h core_uds=%b core_lds=%b bus_rw=%b bus_as=%b bus_addr=%08h bus_dout=%04h bus_uds=%b bus_lds=%b dtack=%b selRAM=%b ram_we=%b ram_addr=%07h ram_ds=%b ram_din=%04h B0B22=%02h",
				         lowmem_bset_raw_hits,
				         last_fetch_pc,
				         last_fetch_opcode,
				         tg68k_inst.tg68k.opcode,
				         tg68k_inst.tg68k.exe_opcode,
				         tg68k_inst.tg68k.sndopc,
				         tg68k_inst.tg68k.micro_state,
				         tg68k_inst.tg68k.next_micro_state,
				         tg68k_inst.tg68k.decodeopc,
				         tg68k_inst.tg68k.execopc,
				         tg68k_inst.tg68k.setexecopc,
				         tg68k_inst.tg68k.nextpass,
				         tg68k_inst.tg68k.setnextpass,
				         tg68k_inst.tg68k.write_back,
				         tg68k_inst.tg68k.exec_write_back,
				         tg68k_inst.tg68k.ea_build_now,
				         tg68k_inst.tg68k.set[42],
				         tg68k_inst.tg68k.set_exec[42],
				         tg68k_inst.tg68k.set[71],
				         tg68k_inst.tg68k.set_exec[71],
				         tg68k_inst.tg68k.set[14],
				         tg68k_inst.tg68k.set_exec[14],
				         tg68k_inst.tg68k.set[26],
				         tg68k_inst.tg68k.set_exec[26],
				         cpu_en_p,
				         cpu_en_n,
				         tg68k_inst.tg68_busstate,
				         tg68k_inst.s_state,
				         tg68k_inst.tg68_rw,
				         tg68k_inst.tg68_addr,
				         tg68_dout,
				         tg68k_inst.tg68_uds_n,
				         tg68k_inst.tg68_lds_n,
				         _cpuRW,
				         _cpuAS,
				         cpuAddr,
				         cpuDataOut,
				         _cpuUDS,
				         _cpuLDS,
				         _cpuDTACK,
				         selectRAM,
				         ram_we,
				         ram_addr,
				         ram_ds,
				         ram_din,
				         ram_do_raw[15:8]);
				lowmem_bset_raw_hits <= lowmem_bset_raw_hits + 1;
			end
		end

		if ($test$plusargs("lowmem_bit_raw_debug") && lowmem_bit_raw_dbg_hits < 256) begin
			if ((last_fetch_pc >= 32'h4080DC80 && last_fetch_pc <= 32'h4080DC92) ||
			    (tg68k_inst.tg68_addr[31:1] == 31'h00000591) ||
			    (tg68_a[31:1] == 31'h00000591) ||
			    (ram_addr[21:0] == 22'h000591 && ram_we)) begin
				$display("LOWMEM_RAW[%0d] pc=%08h op=%04h phi1=%b phi2=%b core_state=%b wrap_state=%0d core_rw=%b core_addr=%08h core_dout=%04h core_uds=%b core_lds=%b bus_rw=%b bus_as=%b bus_addr=%08h bus_dout=%04h bus_uds=%b bus_lds=%b dtack=%b selRAM=%b ram_we=%b ram_addr=%07h ram_ds=%b ram_din=%04h B0B22=%02h",
				         lowmem_bit_raw_dbg_hits,
				         last_fetch_pc,
				         last_fetch_opcode,
				         cpu_en_p,
				         cpu_en_n,
				         tg68k_inst.tg68_busstate,
				         tg68k_inst.s_state,
				         tg68k_inst.tg68_rw,
				         tg68k_inst.tg68_addr,
				         tg68_dout,
				         tg68k_inst.tg68_uds_n,
				         tg68k_inst.tg68_lds_n,
				         _cpuRW,
				         _cpuAS,
				         cpuAddr,
				         cpuDataOut,
				         _cpuUDS,
				         _cpuLDS,
				         _cpuDTACK,
				         selectRAM,
				         ram_we,
				         ram_addr,
				         ram_ds,
				         ram_din,
				         ram_do_raw[15:8]);
				lowmem_bit_raw_dbg_hits <= lowmem_bit_raw_dbg_hits + 1;
			end
		end
	end

	function [31:0] tg68_dbg_reg(input [3:0] idx);
		tg68_dbg_reg = {tg68k_inst.tg68k.regfile_n2[idx], tg68k_inst.tg68k.regfile_n1[idx]};
	endfunction

	function [31:0] asc_dbg_hash_a;
		integer idx;
		begin
			asc_dbg_hash_a = 32'h811c9dc5;
			for (idx = 0; idx < 1024; idx = idx + 1)
				asc_dbg_hash_a = (asc_dbg_hash_a ^ dc0.asc_inst.ram_a[idx]) * 32'h01000193;
		end
	endfunction

	function [31:0] asc_dbg_hash_b;
		integer idx;
		begin
			asc_dbg_hash_b = 32'h811c9dc5;
			for (idx = 0; idx < 1024; idx = idx + 1)
				asc_dbg_hash_b = (asc_dbg_hash_b ^ dc0.asc_inst.ram_b[idx]) * 32'h01000193;
		end
	endfunction

	task asc_dbg_state(input [31:0] pc, input [31:0] hit);
		begin
			$display("[ASC_STATE] hit=%0d pc=%08h d2=%08h d3=%08h d4=%08h d7=%08h a0=%08h a3=%08h mode=%02h ctl=%02h fifo_mode=%02h fifo_irq=%02h wt=%02h vol=%02h clk=%02h fa_wp=%03h fa_rp=%03h fa_cnt=%04h fb_wp=%03h fb_rp=%03h fb_cnt=%04h hash_a=%08h hash_b=%08h a0_0f=%02h%02h%02h%02h_%02h%02h%02h%02h_%02h%02h%02h%02h_%02h%02h%02h%02h b0_0f=%02h%02h%02h%02h_%02h%02h%02h%02h_%02h%02h%02h%02h_%02h%02h%02h%02h",
			         hit, pc,
			         tg68_dbg_reg(4'd2), tg68_dbg_reg(4'd3),
			         tg68_dbg_reg(4'd4), tg68_dbg_reg(4'd7),
			         tg68_dbg_reg(4'd8), tg68_dbg_reg(4'd11),
			         dc0.asc_inst.asc_mode,
			         dc0.asc_inst.asc_control,
			         dc0.asc_inst.asc_fifo_mode,
			         dc0.asc_inst.asc_fifo_irq,
			         dc0.asc_inst.asc_wt_control,
			         dc0.asc_inst.asc_volume,
			         dc0.asc_inst.asc_clock_rate,
			         dc0.asc_inst.fifo_a_wr_ptr,
			         dc0.asc_inst.fifo_a_rd_ptr,
			         dc0.asc_inst.fifo_a_count,
			         dc0.asc_inst.fifo_b_wr_ptr,
			         dc0.asc_inst.fifo_b_rd_ptr,
			         dc0.asc_inst.fifo_b_count,
			         asc_dbg_hash_a(), asc_dbg_hash_b(),
			         dc0.asc_inst.ram_a[0], dc0.asc_inst.ram_a[1],
			         dc0.asc_inst.ram_a[2], dc0.asc_inst.ram_a[3],
			         dc0.asc_inst.ram_a[4], dc0.asc_inst.ram_a[5],
			         dc0.asc_inst.ram_a[6], dc0.asc_inst.ram_a[7],
			         dc0.asc_inst.ram_a[8], dc0.asc_inst.ram_a[9],
			         dc0.asc_inst.ram_a[10], dc0.asc_inst.ram_a[11],
			         dc0.asc_inst.ram_a[12], dc0.asc_inst.ram_a[13],
			         dc0.asc_inst.ram_a[14], dc0.asc_inst.ram_a[15],
			         dc0.asc_inst.ram_b[0], dc0.asc_inst.ram_b[1],
			         dc0.asc_inst.ram_b[2], dc0.asc_inst.ram_b[3],
			         dc0.asc_inst.ram_b[4], dc0.asc_inst.ram_b[5],
			         dc0.asc_inst.ram_b[6], dc0.asc_inst.ram_b[7],
			         dc0.asc_inst.ram_b[8], dc0.asc_inst.ram_b[9],
			         dc0.asc_inst.ram_b[10], dc0.asc_inst.ram_b[11],
			         dc0.asc_inst.ram_b[12], dc0.asc_inst.ram_b[13],
			         dc0.asc_inst.ram_b[14], dc0.asc_inst.ram_b[15]);
		end
	endtask

	reg [31:0] asc_state_prev_pc;
	reg [31:0] asc_state_hits;

	always @(posedge clk_sys) begin
		if ($test$plusargs("asc_state_debug") && last_fetch_pc != asc_state_prev_pc) begin
			asc_state_prev_pc <= last_fetch_pc;
			if (last_fetch_pc == 32'h40805E4A ||
			    last_fetch_pc == 32'h40805F14 ||
			    last_fetch_pc == 32'h40805F28 ||
			    last_fetch_pc == 32'h40805F5C ||
			    last_fetch_pc == 32'h40805F60 ||
			    last_fetch_pc == 32'h40805F78) begin
				asc_state_hits <= asc_state_hits + 1'd1;
				if (asc_state_hits < 32 ||
				    last_fetch_pc == 32'h40805E4A ||
				    last_fetch_pc == 32'h40805F14 ||
				    last_fetch_pc == 32'h40805F78 ||
				    tg68_dbg_reg(2) == 32'h00001095 ||
				    tg68_dbg_reg(2) == 32'h00000DF1 ||
				    asc_state_hits[10:0] == 11'h000)
					asc_dbg_state(last_fetch_pc, asc_state_hits);
			end
		end
	end

	reg [31:0] asc_rom_dbg_prev_pc;
	reg [31:0] asc_rom_dbg_bus_count;
	reg [31:0] asc_rom_dbg_f5c_hits;
	reg        asc_rom_dbg_bus_active;

	function asc_rom_dbg_interesting_pc;
		input [31:0] pc;
		begin
			asc_rom_dbg_interesting_pc = (pc == 32'h40805E4A ||
			                              pc == 32'h40805E70 ||
			                              pc == 32'h40805E74 ||
			                              pc == 32'h40805E78 ||
			                              pc == 32'h40805E7C ||
			                              pc == 32'h40805E80 ||
			                              pc == 32'h40805E82 ||
			                              pc == 32'h40805E84 ||
			                              pc == 32'h40805E8C ||
			                              pc == 32'h40805E94 ||
			                              pc == 32'h40805ED6 ||
			                              pc == 32'h40805EE6 ||
			                              pc == 32'h40805F14 ||
			                              pc == 32'h40805F28 ||
			                              pc == 32'h40805F5C ||
			                              pc == 32'h40805F60 ||
			                              pc == 32'h40805F78);
		end
	endfunction

	always @(posedge clk_sys) begin
		if ($test$plusargs("asc_rom_debug")) begin
			if (last_fetch_pc != asc_rom_dbg_prev_pc) begin
				asc_rom_dbg_prev_pc <= last_fetch_pc;
				if (asc_rom_dbg_interesting_pc(last_fetch_pc)) begin
					$display("[ASC_ROM_PC] pc=%08h d0=%08h d1=%08h d2=%08h d3=%08h d4=%08h d7=%08h a0=%08h a3=%08h a4=%08h",
					         last_fetch_pc,
					         tg68_dbg_reg(4'd0), tg68_dbg_reg(4'd1),
					         tg68_dbg_reg(4'd2), tg68_dbg_reg(4'd3),
					         tg68_dbg_reg(4'd4), tg68_dbg_reg(4'd7),
					         tg68_dbg_reg(4'd8), tg68_dbg_reg(4'd11),
					         tg68_dbg_reg(4'd12));
				end
				if (last_fetch_pc == 32'h40805F5C) begin
					asc_rom_dbg_f5c_hits <= asc_rom_dbg_f5c_hits + 1'd1;
					if (asc_rom_dbg_f5c_hits[7:0] == 8'h00) begin
						$display("[ASC_ROM_PROGRESS] f5c_hits=%0d d3=%08h d4=%08h d7=%08h a0=%08h",
						         asc_rom_dbg_f5c_hits,
						         tg68_dbg_reg(4'd3), tg68_dbg_reg(4'd4),
						         tg68_dbg_reg(4'd7), tg68_dbg_reg(4'd8));
					end
				end
			end

			if (tg68_as_n || !selectASC || (_cpuUDS && _cpuLDS)) begin
				asc_rom_dbg_bus_active <= 1'b0;
			end else if (!asc_rom_dbg_bus_active && asc_rom_dbg_bus_count < 128) begin
				asc_rom_dbg_bus_active <= 1'b1;
				$display("[ASC_ROM_BUS] pc=%08h rw=%b addr=%08h din=%04h dout=%04h ds=%b d3=%08h d7=%08h",
				         last_fetch_pc, _cpuRW, cpuAddr, cpuDataOut,
				         dataControllerDataOut, {~_cpuUDS, ~_cpuLDS},
				         tg68_dbg_reg(4'd3), tg68_dbg_reg(4'd7));
				asc_rom_dbg_bus_count <= asc_rom_dbg_bus_count + 1'd1;
			end
		end
	end

	reg [31:0] asc_entry_dbg_prev_pc;
	reg [31:0] asc_entry_dbg_hits;

	function asc_entry_dbg_interesting_pc;
		input [31:0] pc;
		begin
			asc_entry_dbg_interesting_pc = (pc == 32'h408000D0 ||
			                                pc == 32'h40802CDC ||
			                                pc == 32'h40802CE2 ||
			                                pc == 32'h40802CE4 ||
			                                pc == 32'h40802CEA ||
			                                pc == 32'h40802CEE ||
			                                pc == 32'h40805E4A ||
			                                pc == 32'h40805E5C ||
			                                pc == 32'h40805E62 ||
			                                pc == 32'h40805E66 ||
			                                pc == 32'h40805E68 ||
			                                pc == 32'h40805E6E ||
			                                pc == 32'h40805E70);
		end
	endfunction

	always @(posedge clk_sys) begin
		if ($test$plusargs("asc_entry_debug") && last_fetch_pc != asc_entry_dbg_prev_pc) begin
			asc_entry_dbg_prev_pc <= last_fetch_pc;
			if (asc_entry_dbg_interesting_pc(last_fetch_pc) && asc_entry_dbg_hits < 128) begin
				$display("[ASC_ENTRY] hit=%0d pc=%08h d0=%08h d7=%08h a0=%08h a3=%08h a4=%08h a6=%08h pa=%02h ira=%02h ddra=%02h",
				         asc_entry_dbg_hits, last_fetch_pc,
				         tg68_dbg_reg(4'd0), tg68_dbg_reg(4'd7),
				         tg68_dbg_reg(4'd8), tg68_dbg_reg(4'd11),
				         tg68_dbg_reg(4'd12), tg68_dbg_reg(4'd14),
				         dc0.via.pio_i_pra, dc0.via.ira, dc0.via.pio_i_ddra);
				asc_entry_dbg_hits <= asc_entry_dbg_hits + 1'd1;
			end
		end
	end

	reg [31:0] ramtest_dbg_prev_pc;
	reg [31:0] ramtest_dbg_hits;
	reg        ramtest_dbg_bus_active;
	reg [31:0] ramtest_dbg_bus_hits;

	function ramtest_dbg_interesting_pc;
		input [31:0] pc;
		begin
			ramtest_dbg_interesting_pc = (pc == 32'h40802BBC ||
			                              pc == 32'h40802BF0 ||
			                              pc == 32'h40802C10 ||
			                              pc == 32'h40802C28 ||
			                              pc == 32'h40802C3C ||
			                              pc == 32'h40802CDC ||
			                              pc == 32'h40803714 ||
			                              pc == 32'h40803734 ||
			                              pc == 32'h40803760 ||
			                              pc == 32'h4080378E ||
			                              pc == 32'h40803794 ||
			                              pc == 32'h4080379A ||
			                              pc == 32'h4080379E ||
			                              pc == 32'h408037A0 ||
			                              pc == 32'h408037A2 ||
			                              pc == 32'h408037A4 ||
			                              pc == 32'h408037A6 ||
			                              pc == 32'h408037A8 ||
			                              pc == 32'h408037AA);
		end
	endfunction

	task ramtest_dbg_state;
		input [31:0] pc;
		input [31:0] hit;
		begin
			$display("[RAMTEST] hit=%0d pc=%08h d0=%08h d1=%08h d2=%08h d3=%08h d4=%08h d5=%08h d6=%08h d7=%08h a0=%08h a1=%08h a2=%08h a3=%08h a4=%08h a6=%08h via2_pa_o=%02h via2_pa_i=%02h via2_ddra=%02h via2_ira=%02h glue=%02b m0=%04h%04h m8=%04h%04h msp=%04h%04h mtop=%04h%04h",
			         hit, pc,
			         tg68_dbg_reg(4'd0), tg68_dbg_reg(4'd1),
			         tg68_dbg_reg(4'd2), tg68_dbg_reg(4'd3),
			         tg68_dbg_reg(4'd4), tg68_dbg_reg(4'd5),
			         tg68_dbg_reg(4'd6), tg68_dbg_reg(4'd7),
			         tg68_dbg_reg(4'd8), tg68_dbg_reg(4'd9),
			         tg68_dbg_reg(4'd10), tg68_dbg_reg(4'd11),
			         tg68_dbg_reg(4'd12), tg68_dbg_reg(4'd14),
			         dc0.via2_pa_o, dc0.via2_pa_i, dc0.via2.pio_i_ddra,
			         dc0.via2.ira, glueRAMSize,
			         ram.mem[22'h000000], ram.mem[22'h000001],
			         ram.mem[22'h000004], ram.mem[22'h000005],
			         ram.mem[22'h0ffe80], ram.mem[22'h0ffe81],
			         ram.mem[22'h0ffffe], ram.mem[22'h0fffff]);
		end
	endtask

	always @(posedge clk_sys) begin
		if ($test$plusargs("ramtest_debug")) begin
			if (last_fetch_pc != ramtest_dbg_prev_pc) begin
				ramtest_dbg_prev_pc <= last_fetch_pc;
				if (ramtest_dbg_interesting_pc(last_fetch_pc) &&
				    (last_fetch_pc != 32'h4080378E || tg68_dbg_reg(4'd5) <= 32'd4) &&
				    ramtest_dbg_hits < 240) begin
					ramtest_dbg_state(last_fetch_pc, ramtest_dbg_hits);
					ramtest_dbg_hits <= ramtest_dbg_hits + 1'd1;
				end
			end

			if ($test$plusargs("ramtest_bus_debug")) begin
				if (tg68_as_n || (!selectRAM && !selectROM) || (_cpuUDS && _cpuLDS)) begin
					ramtest_dbg_bus_active <= 1'b0;
				end else if (!ramtest_dbg_bus_active &&
				             last_fetch_pc >= 32'h40803710 &&
				             last_fetch_pc <= 32'h408037AA &&
				             ramtest_dbg_bus_hits < 96) begin
					ramtest_dbg_bus_active <= 1'b1;
					$display("[RAMTEST_BUS] hit=%0d pc=%08h rw=%b tg68_a=%08h cpuAddr=%08h memAddr=%06h ramAddr=%07h din=%04h dout=%04h ramdo=%04h ds=%b selRAM=%b selROM=%b overlay=%b",
					         ramtest_dbg_bus_hits, last_fetch_pc, _cpuRW,
					         tg68_a, cpuAddr, memoryAddr, ram_addr,
					         cpuDataOut, dataControllerDataOut, ram_do_raw,
					         {~_cpuUDS, ~_cpuLDS}, selectRAM, selectROM,
					         memoryOverlayOn);
					ramtest_dbg_bus_hits <= ramtest_dbg_bus_hits + 1'd1;
				end
			end
		end
	end

	always @(posedge clk_sys) begin
		if ($test$plusargs("via2_debug") && !_cpuVMA && selectVIA2 && E_falling) begin
			$display("[VIA2_%s] pc=%08h addr=%08h reg=%1h data=%04h ds=%b pa_o=%02h pa_i=%02h ddra=%02h ira=%02h glue=%02b",
			         _cpuRW ? "RD" : "WR", last_fetch_pc, cpuAddr, cpuAddr[12:9],
			         _cpuRW ? dataControllerDataOut : cpuDataOut,
			         {~_cpuUDS, ~_cpuLDS},
			         dc0.via2_pa_o, dc0.via2_pa_i, dc0.via2.pio_i_ddra,
			         dc0.via2.ira, glueRAMSize);
		end
	end
`endif

`ifdef SIMULATION
	function adb_via_pc_watch;
		input [31:0] pc;
		begin
			adb_via_pc_watch = ((pc >= 32'h40806D00 && pc <= 32'h40806EFF) ||
			                    (pc >= 32'h4080DD00 && pc <= 32'h4080DEFF));
		end
	endfunction

	task adb_via_dbg_state;
		input [8*12-1:0] tag;
		begin
			$display("[ADB_VIA_STATE] tag=%0s pc=%08h d0=%08h d1=%08h d2=%08h a0=%08h via_prb=%02h via_ddrb=%02h via_irb=%02h via_pbi=%02h acr=%02h pcr=%02h sr=%02h ifr=%02h ier=%02h irq=%b st=%b adb_int_n=%b cmd=%02h valid=%b processed=%b resp_len=%0d resp_idx=%0d sr_timer=%0d sr_dir=%b sr_shadow=%02h kbd_to_mac=%02h",
			         tag, last_fetch_pc,
			         tg68_dbg_reg(4'd0), tg68_dbg_reg(4'd1),
			         tg68_dbg_reg(4'd2), tg68_dbg_reg(4'd8),
			         dc0.via.pio_i_prb, dc0.via.pio_i_ddrb,
			         dc0.via.irb, dc0.via.port_b_i,
			         dc0.via.acr, dc0.via.pcr, dc0.via.shift_reg,
			         {dc0.via.irq_out, dc0.via.irq_flags}, {1'b1, dc0.via.irq_mask}, dc0.viaIrq,
			         {dc0.ADBST1, dc0.ADBST0}, dc0._ADBint,
			         dc0.adb.cmd_byte, dc0.adb.cmd_valid, dc0.adb.cmd_processed,
			         dc0.adb.resp_len, dc0.adb.resp_idx,
			         dc0.via1_shift_timer, dc0.via1_shift_dir,
			         dc0.via1_sr_shadow, dc0.kbd_to_mac);
		end
	endtask

	reg [31:0] adb_via_prev_pc;
	reg [15:0] adb_via_prints;
	always @(posedge clk_sys) begin
		if ($test$plusargs("adb_via_debug")) begin
			if (last_fetch_pc != adb_via_prev_pc) begin
				adb_via_prev_pc <= last_fetch_pc;
				if (adb_via_pc_watch(last_fetch_pc) && adb_via_prints < 16'd300) begin
					adb_via_dbg_state("pc");
					adb_via_prints <= adb_via_prints + 1'd1;
				end
			end

			if ((dc0.via.ren || dc0.via.wen) && dc0.via.falling && adb_via_prints < 16'd900) begin
				$display("[ADB_VIA_BUS] pc=%08h rw=%b reg=%01h addr=%08h din=%02h dout=%02h prb=%02h ddrb=%02h irb=%02h pbi=%02h acr=%02h pcr=%02h sr=%02h ifr=%02h ier=%02h st=%b adb_int_n=%b timer=%0d shadow=%02h kbd=%02h",
				         last_fetch_pc, dc0.via.ren, dc0.via.addr, cpuAddr,
				         dc0.via.data_in, dc0.via.data_out,
				         dc0.via.pio_i_prb, dc0.via.pio_i_ddrb,
				         dc0.via.irb, dc0.via.port_b_i,
				         dc0.via.acr, dc0.via.pcr, dc0.via.shift_reg,
				         {dc0.via.irq_out, dc0.via.irq_flags}, {1'b1, dc0.via.irq_mask},
				         {dc0.ADBST1, dc0.ADBST0}, dc0._ADBint,
				         dc0.via1_shift_timer, dc0.via1_sr_shadow, dc0.kbd_to_mac);
				adb_via_prints <= adb_via_prints + 1'd1;
			end

			if ((dc0.adb_din_strobe || dc0.adb_dout_strobe || dc0.via1_sr_ext_complete) && adb_via_prints < 16'd900) begin
				$display("[ADB_VIA_EVT] pc=%08h din_stb=%b din=%02h dout_stb=%b dout=%02h sr_done=%b sr_load=%b st=%b adb_int_n=%b cmd=%02h valid=%b processed=%b resp_len=%0d resp_idx=%0d",
				         last_fetch_pc, dc0.adb_din_strobe, dc0.adb_din,
				         dc0.adb_dout_strobe, dc0.adb_dout,
				         dc0.via1_sr_ext_complete, dc0.via1_sr_ext_load,
				         {dc0.ADBST1, dc0.ADBST0}, dc0._ADBint,
				         dc0.adb.cmd_byte, dc0.adb.cmd_valid, dc0.adb.cmd_processed,
				         dc0.adb.resp_len, dc0.adb.resp_idx);
				adb_via_prints <= adb_via_prints + 1'd1;
			end
		end
	end
`endif


`ifdef LEGACY_DEBUG
	// Dump interrupt dispatch table when ROM enables CA1/CA2 IRQs (IER=0x03).
	// The dispatcher at $40806080 does JSR through a table; bits 0/1 map to
	// CA2/CA1. If those entries are RTS stubs, nothing ever clears IFR.
	// We also watch for the target of JSR (A0) at $408060AA by logging
	// the next fetch.
	reg [6:0] dbg_ier_d;
	reg dbg_dumped;
	integer di;
	always @(posedge clk_sys) begin
		dbg_ier_d <= dc0.via.irq_mask;
		if (!dbg_dumped && dc0.via.irq_mask == 7'h03 && dbg_ier_d != 7'h03) begin
			dbg_dumped <= 1'b1;
			$display("[DUMP] IER just became 03 — RAM bytes 0x0180..0x01FF:");
			for (di = 22'h00C0; di < 22'h0100; di = di + 1)
				$display("  word[%04h] byte[%04h] = %04h", di[11:0], di[11:0]<<1, ram.mem[di]);
			$display("[DUMP] RAM bytes 0x1FFE0..0x1FFFF (A3 area):");
			for (di = 22'hFFF0; di < 22'h10000; di = di + 1)
				$display("  word[%05h] byte[%05h] = %04h", di[19:0], di[19:0]<<1, ram.mem[di]);
		end
	end

	// Log handler target: when PC is at $408060AA (JSR (A0)), the next PC
	// that is fetched will be the handler address the dispatcher jumped to.
	reg [31:0] last_fetch_pc_d;
	reg dbg_waiting_target;
	always @(posedge clk_sys) begin
		last_fetch_pc_d <= last_fetch_pc;
		if (last_fetch_pc == 32'h408060AA && last_fetch_pc_d != 32'h408060AA)
			dbg_waiting_target <= 1'b1;
		else if (dbg_waiting_target && last_fetch_pc != 32'h408060AA
		         && last_fetch_pc != last_fetch_pc_d) begin
			$display("[JSR_TGT] dispatcher JSR target PC = %08h", last_fetch_pc);
			dbg_waiting_target <= 1'b0;
		end
	end

	// Probe ASC register-bank writes ($50F14800..$50F1481F): mode/control/
	// volume etc. — tells us if POST actually programmed the chime.
	reg [31:0] asc_reg_writes;
	always @(posedge clk_sys) begin
		if (!tg68_as_n && !tg68_rw
		    && tg68_a[31:12] == 20'h50F14
		    && tg68_a[11]                      // $800..$FFF range
		    && asc_reg_writes < 40) begin
			$display("[ASC_REGWR] PC=%08h addr=%08h data=%04h ds=%b",
			         last_fetch_pc, tg68_a, memoryDataOut,
			         {~_memoryUDS, ~_memoryLDS});
			asc_reg_writes <= asc_reg_writes + 1;
		end
	end

	// Probe entry to the SCC-polling dispatch routine. Start address
	// $40803280 is a generous window to catch the JSR target / routine
	// entry point. Log the last 6 distinct PCs before first entry.
	reg        saw_33xx;
	reg [31:0] pre_33xx [0:7];
	reg [2:0]  pre_33xx_idx;
	always @(posedge clk_sys) begin
		if (!saw_33xx) begin
			pre_33xx[pre_33xx_idx] <= last_fetch_pc;
			pre_33xx_idx <= pre_33xx_idx + 1;
			if (last_fetch_pc >= 32'h40803280 && last_fetch_pc <= 32'h40803290) begin
				saw_33xx <= 1'b1;
				$display("[MONITOR_ENTRY] first fetch in range = %08h", last_fetch_pc);
				$display("  history[-7]=%08h", pre_33xx[(pre_33xx_idx+1) & 3'h7]);
				$display("  history[-6]=%08h", pre_33xx[(pre_33xx_idx+2) & 3'h7]);
				$display("  history[-5]=%08h", pre_33xx[(pre_33xx_idx+3) & 3'h7]);
				$display("  history[-4]=%08h", pre_33xx[(pre_33xx_idx+4) & 3'h7]);
				$display("  history[-3]=%08h", pre_33xx[(pre_33xx_idx+5) & 3'h7]);
				$display("  history[-2]=%08h", pre_33xx[(pre_33xx_idx+6) & 3'h7]);
				$display("  history[-1]=%08h", pre_33xx[(pre_33xx_idx+7) & 3'h7]);
			end
		end
	end

	// Call-chain probe for the stuck SCC Rx poll.
	// $408032A0 is the polling routine's entry; $40803304 is its JMP (A6)
	// exit. The PC fetched after $40803304 is the caller's return address.
	// Capture (a) how many times we enter $408032A0, and (b) the first 8
	// distinct return addresses observed after the JMP (A6).
	reg [31:0] poll_entry_count;
	reg [31:0] poll_entry_last_fetch;  // PC just before $408032A0
	reg        poll_entry_seen;
	reg [31:0] poll_ret_count;
	reg        poll_ret_pending;
	always @(posedge clk_sys) begin
		// Entry edge into $408032A0
		if (last_fetch_pc == 32'h408032A0 && !poll_entry_seen) begin
			poll_entry_seen <= 1'b1;
			poll_entry_count <= poll_entry_count + 1;
			if (poll_entry_count < 8)
				$display("[POLL_ENTRY] #%0d  prev_fetch=%08h (caller side)",
				         poll_entry_count, poll_entry_last_fetch);
		end else if (last_fetch_pc != 32'h408032A0) begin
			poll_entry_seen <= 1'b0;
			poll_entry_last_fetch <= last_fetch_pc;
		end

		// Arm capture of PC after JMP (A6) at $40803304
		if (last_fetch_pc == 32'h40803304)
			poll_ret_pending <= 1'b1;
		else if (poll_ret_pending) begin
			if (last_fetch_pc != 32'h40803304) begin
				poll_ret_pending <= 1'b0;
				if (poll_ret_count < 8) begin
					poll_ret_count <= poll_ret_count + 1;
					$display("[POLL_RET ] #%0d  JMP (A6) went to PC=%08h",
					         poll_ret_count, last_fetch_pc);
				end
			end
		end
	end

	// RAM-test tracker: count JSRs into $40802BBC (orchestrator) and log
	// every bus write whose data word is $6DB6 (the test pattern's high
	// half). Each run of the pattern starts writes at A2 (bank boundary)
	// ascending to A1. First $6DB6 write of a run = where the test began.
	reg [31:0] bbc_entries;
	reg        bbc_pc_seen;
	reg [31:0] pat_writes;
	reg [31:0] pat_reads;
	reg [31:0] pat_we_pulses;
	always @(posedge clk_sys) begin
		if (last_fetch_pc == 32'h40802BBC && !bbc_pc_seen) begin
			bbc_pc_seen <= 1'b1;
			bbc_entries <= bbc_entries + 1;
			$display("[BBC_ENTRY] #%0d  prev=%08h", bbc_entries, post_prev_pc);
		end else if (last_fetch_pc != 32'h40802BBC) begin
			bbc_pc_seen <= 1'b0;
		end
		// Reads in $0..$40 but ONLY while inside RAM-test routine $40803700-$40803800.
		if (!tg68_as_n && tg68_rw && tg68_a < 32'h40
		    && last_fetch_pc[31:8] == 24'h408037
		    && pat_reads < 24) begin
			$display("[PAT_RD] #%0d PC=%08h tg68_a=%08h cpuAddr=%08h selROM=%b selRAM=%b",
			         pat_reads, last_fetch_pc, tg68_a, cpuAddr,
			         !_romOE, !_ramOE);
			pat_reads <= pat_reads + 1;
		end
		// Probe actual ram_we pulses during the RAM test (PC inside $40803700-$40803800)
		if (ram_we && ram_addr < 25'h20
		    && last_fetch_pc[31:8] == 24'h408037
		    && pat_we_pulses < 20) begin
			$display("[RAM_WE] #%0d PC=%08h ram_addr=%07h ram_din=%04h ds=%b",
			         pat_we_pulses, last_fetch_pc, ram_addr, ram_din, ram_ds);
			pat_we_pulses <= pat_we_pulses + 1;
		end
		if (!tg68_as_n && !tg68_rw && memoryDataOut == 16'h6DB6
		    && pat_writes < 20) begin
			$display("[PAT_WR] #%0d PC=%08h tg68_a=%08h cpuAddr=%08h overlay=%b selROM=%b selRAM=%b",
			         pat_writes, last_fetch_pc, tg68_a, cpuAddr,
			         memoryOverlayOn, !_romOE, !_ramOE);
			pat_writes <= pat_writes + 1;
		end
	end

	// POST failure probe: ring-buffer of the last 16 distinct fetched PCs,
	// dumped on first fetch of $40802C3C (POST failure entry point). The PC
	// just before $40802C3C (typically a BNE.W inside $40802AFA..$40802B7C)
	// uniquely identifies which POST subroutine reported failure.
	reg [31:0] post_hist [0:15];
	reg [3:0]  post_hist_idx;
	reg [31:0] post_prev_pc;
	reg        post_fail_seen;
	integer    post_i;
	always @(posedge clk_sys) begin
		if (!post_fail_seen && last_fetch_pc != post_prev_pc) begin
			post_hist[post_hist_idx] <= last_fetch_pc;
			post_hist_idx <= post_hist_idx + 4'd1;
			post_prev_pc  <= last_fetch_pc;
			if (last_fetch_pc == 32'h40802C3C) begin
				post_fail_seen <= 1'b1;
				$display("[POST_FAIL] reached $40802C3C failure entry");
				$display("  ram.mem[0]=%04h [1]=%04h [2]=%04h [3]=%04h [4]=%04h [5]=%04h [6]=%04h [7]=%04h",
				         ram.mem[0], ram.mem[1], ram.mem[2], ram.mem[3],
				         ram.mem[4], ram.mem[5], ram.mem[6], ram.mem[7]);
				for (post_i = 0; post_i < 16; post_i = post_i + 1) begin
					$display("  hist[-%0d] = %08h",
					         16 - post_i,
					         post_hist[(post_hist_idx + post_i[3:0]) & 4'hF]);
				end
			end
		end
	end

	// $408032AC entry tracker + 16-PC ring before first entry
	reg [31:0] tac_ring [0:15];
	reg [3:0]  tac_idx;
	reg [31:0] tac_prev_pc;
	reg        tac_seen;
	integer    tac_i;
	always @(posedge clk_sys) begin
		if (!tac_seen && last_fetch_pc != tac_prev_pc) begin
			tac_ring[tac_idx] <= last_fetch_pc;
			tac_idx <= tac_idx + 1;
			tac_prev_pc <= last_fetch_pc;
			if (last_fetch_pc == 32'h408032AC) begin
				tac_seen <= 1;
				$display("[TAC_ENTRY] first hit $408032AC, 16 PCs leading:");
				for (tac_i = 0; tac_i < 16; tac_i = tac_i + 1)
					$display("  [-%0d] %08h", 16 - tac_i,
					         tac_ring[(tac_idx + tac_i[3:0]) & 4'hF]);
			end
		end
	end

	// VBR change tracker — log every transition with the new value + PC.
	// VBR should only change on MOVEC to VBR; an odd/misaligned value is a bug.
	reg [31:0] vbr_prev;
	always @(posedge clk_sys) begin
		if (debug_vbr != vbr_prev) begin
			$display("[VBR_CHG] %08h -> %08h at PC=%08h (odd=%b)",
			         vbr_prev, debug_vbr, last_fetch_pc, debug_vbr[0]);
			vbr_prev <= debug_vbr;
		end
	end

	// IRQ + throughput profiler. Counts IPL assert edges per level and
	// instruction fetches per report window.
	reg [31:0] prof_cyc;
	reg [31:0] prof_fetches;
	reg [31:0] prof_irq1, prof_irq2, prof_irq4, prof_irq7;
	reg [2:0]  prof_ipl_prev;
	reg [31:0] prof_fetch_prev;
	always @(posedge clk_sys) begin
		prof_cyc <= prof_cyc + 1;
		if (last_fetch_pc != prof_fetch_prev) begin
			prof_fetches <= prof_fetches + 1;
			prof_fetch_prev <= last_fetch_pc;
		end
		// _cpuIPL active-low: count edges where IPL goes from 7 (inactive)
		// down to a lower value (assertion).
		if (prof_ipl_prev == 3'b111 && _cpuIPL != 3'b111) begin
			case (_cpuIPL)
				3'b110: prof_irq1 <= prof_irq1 + 1;
				3'b101: prof_irq2 <= prof_irq2 + 1;
				3'b011: prof_irq4 <= prof_irq4 + 1;
				3'b000: prof_irq7 <= prof_irq7 + 1;
				default: ;
			endcase
		end
		prof_ipl_prev <= _cpuIPL;
		// Report every ~16M sys_clks (~0.5 sec wall)
		if (prof_cyc[23:0] == 24'h000000 && prof_cyc != 0) begin
			$display("[PROF] cyc=%0d fetches=%0d irq1=%0d irq2=%0d irq4=%0d irq7=%0d",
			         prof_cyc, prof_fetches, prof_irq1, prof_irq2, prof_irq4, prof_irq7);
		end
	end

	// Outer wavetable-scramble loop progress: count $40805F5C hits (the
	// dbra D2 at loop bottom). If the counter climbs, we're progressing.
	reg [31:0] f5c_hits;
	reg [31:0] f14_hits;
	reg [31:0] f5c_last_report;
	reg [31:0] f5c_prev_pc;
	always @(posedge clk_sys) begin
		if (last_fetch_pc == 32'h40805F5C && f5c_prev_pc != 32'h40805F5C)
			f5c_hits <= f5c_hits + 1;
		if (last_fetch_pc == 32'h40805F14 && f5c_prev_pc != 32'h40805F14) begin
			f14_hits <= f14_hits + 1;
			$display("[F14_ENTRY #%0d] prev_pc=%08h", f14_hits, f5c_prev_pc);
		end
		f5c_prev_pc <= last_fetch_pc;
		if ((f5c_hits - f5c_last_report) >= 256) begin
			$display("[F5C_PROGRESS] hits=%0d f14=%0d", f5c_hits, f14_hits);
			f5c_last_report <= f5c_hits;
		end
	end

	// Late boot polling loop at $408268F2/$408268F8. The ROM polls bit 6 of
	// (A3+$10); log A3 and the translated bus address/data to identify the
	// device holding boot.
	reg [7:0] poll268_prints = 8'd0;
	always @(posedge clk_sys) begin
		if ($test$plusargs("poll268_debug") && poll268_prints < 8'd80) begin
			if (last_fetch_pc >= 32'h408268d8 && last_fetch_pc <= 32'h40826930) begin
				$display("[POLL268] pc=%08h op=%04h addr=%08h rw=%b din=%04h dout=%04h d0=%08h d1=%08h d5=%08h d7=%08h a3=%08h a4=%08h hmmu=%b selSCSI=%b selSCC=%b selVIA=%b selVIA2=%b selNuBus=%b selRAM=%b",
				         last_fetch_pc, tg68k_inst.tg68k.opc_in, cpuAddr,
				         _cpuRW, cpuDataIn, cpuDataOut,
				         tg68_dbg_reg(4'd0), tg68_dbg_reg(4'd1),
				         tg68_dbg_reg(4'd5), tg68_dbg_reg(4'd7),
				         tg68_dbg_reg(4'd11), tg68_dbg_reg(4'd12),
				         hmmu_active, selectSCSI, selectSCC, selectVIA,
				         selectVIA2, selectNuBus, selectRAM);
				poll268_prints <= poll268_prints + 1'd1;
			end
		end
	end

	// Test-routine entry/exit counter: how many times does $40803714 (start)
	// fire vs $408037AA (JMP (A6) return)? Also log first 8 orchestrator
	// PC transitions after each return to see pass/fail branch decision.
	reg [15:0] test_enter_cnt;
	reg [15:0] test_exit_cnt;
	reg [31:0] test_last_pc;
	reg [3:0]  post_ret_window;
	always @(posedge clk_sys) begin
		if (last_fetch_pc != test_last_pc) begin
			test_last_pc <= last_fetch_pc;
			if (last_fetch_pc == 32'h40803714) begin
				test_enter_cnt <= test_enter_cnt + 1;
				$display("[TEST_ENTER #%0d] pc=%08h", test_enter_cnt, last_fetch_pc);
			end
			if (last_fetch_pc == 32'h408037AA) begin
				test_exit_cnt <= test_exit_cnt + 1;
				$display("[TEST_EXIT #%0d] pc=%08h", test_exit_cnt, last_fetch_pc);
				post_ret_window <= 4'd8;
			end
			if (post_ret_window != 0 && last_fetch_pc != 32'h408037AA) begin
				$display("[POST_RET] pc=%08h (win=%0d)", last_fetch_pc, post_ret_window);
				post_ret_window <= post_ret_window - 1;
			end
		end
	end
`endif

// synthesis translate_off
// SWIM/ISM trace (2026-08-07): the 1.44MB path stalls at the blinking-? and
// the module's own debug set was never surfaced here. Print the ISM state on
// every change so the failing stage is visible: does the ROM enter ISM mode,
// does drive select assert, do the MFM geometry flags reach the drive, and are
// MFM bytes actually strobing out of the encoder. Enable with +swimtrace.
reg [7:0]  sw_mode_d;  reg sw_ism_d, sw_sel_d, sw_mfm_d, sw_hd_d;
reg [15:0] sw_bcnt_d;  reg [7:0] sw_err_d;
always @(posedge clk_sys) begin
	if ($test$plusargs("swimtrace")) begin
		if (dc0.sw.ism_mode !== sw_ism_d || dc0.sw.ism_mode_reg !== sw_mode_d ||
		    dc0.sw.ism_devsel_int !== sw_sel_d || dc0.sw.diskMFM[0] !== sw_mfm_d ||
		    dc0.sw.diskHD[0] !== sw_hd_d || dc0.sw.ism_error !== sw_err_d) begin
			$display("SWIM t=%0t ism_mode=%b mode_reg=%02x devsel_int=%b devsel_ext=%b mfm=%b hd=%b err=%02x fifo=%0d bytecnt=%0d",
			         $time, dc0.sw.ism_mode, dc0.sw.ism_mode_reg, dc0.sw.ism_devsel_int,
			         dc0.sw.ism_devsel_ext, dc0.sw.diskMFM[0], dc0.sw.diskHD[0],
			         dc0.sw.ism_error, dc0.sw.ism_fifo_pos, dc0.sw.dbg_flp_byte_cnt);
		end
		if (dc0.sw.dbg_flp_byte_cnt[9:0] == 10'd0 && dc0.sw.dbg_flp_byte_cnt !== sw_bcnt_d)
			$display("SWIM-MFM t=%0t bytes=%0d (encoder delivering)", $time, dc0.sw.dbg_flp_byte_cnt);
		sw_ism_d <= dc0.sw.ism_mode;   sw_mode_d <= dc0.sw.ism_mode_reg;
		sw_sel_d <= dc0.sw.ism_devsel_int; sw_mfm_d <= dc0.sw.diskMFM[0];
		sw_hd_d  <= dc0.sw.diskHD[0];  sw_err_d  <= dc0.sw.ism_error;
		sw_bcnt_d <= dc0.sw.dbg_flp_byte_cnt;
	end
end
// synthesis translate_on

endmodule

// sim_fpu_cir_stub moved to ../rtl/mc68881/sim_fpu_cir_stub.v so it
// can be shared by other verilator builds (SingleStepTests/cpu_fpu/).
