`timescale 1ns / 1ps
//============================================================================
//  Macintosh II - Verilator Simulation Wrapper
//
//  Adapted from LBMacTwo.sv for simulation
//============================================================================

module emu
(
	input         clk_sys,
	input         reset,

	// PS2 keyboard/mouse
	input [10:0]  ps2_key,
	input [24:0]  ps2_mouse,

	// RTC timestamp
	input [32:0]  timestamp,

	// VGA output
	output [7:0]  VGA_R,
	output [7:0]  VGA_G,
	output [7:0]  VGA_B,
	output        VGA_HS,
	output        VGA_VS,
	output        VGA_HB,
	output        VGA_VB,
	output        CE_PIXEL,

	// Audio output
	output [15:0] AUDIO_L,
	output [15:0] AUDIO_R,

	// ROM/disk loading interface (ioctl)
	input         ioctl_download,
	input         ioctl_wr,
	input [24:0]  ioctl_addr,
	input [15:0]  ioctl_dout,
	input [7:0]   ioctl_index,
	output reg    ioctl_wait = 1'b0,

	// SCSI block device interface
	output [31:0] sd_lba[2],
	output [1:0]  sd_rd,
	output [1:0]  sd_wr,
	input  [1:0]  sd_ack,
	input  [7:0]  sd_buff_addr,
	input  [15:0] sd_buff_dout,
	output [15:0] sd_buff_din[2],
	input         sd_buff_wr,
	input  [1:0]  img_mounted,
	input  [63:0] img_size,

	// CPU debug outputs
	output [31:0] debug_pc,
	output [15:0] debug_opcode,
	output        debug_fetch_valid,
	output  [2:0] debug_fc,           // Function code (2=supv program, 1=supv data, etc)
	output        debug_write_valid,  // Write bus cycle completed
	output [31:0] debug_write_addr,   // Write address
	output [15:0] debug_write_data,   // Write data

	// RAM debug outputs
	output [24:0] debug_ram_addr,
	output [15:0] debug_ram_din,
	output [15:0] debug_ram_dout,
	output        debug_ram_we,
	output        debug_ram_oe,
	output  [1:0] debug_ram_ds,
	output        debug_selectRAM,
	output        debug_selectROM,

	// Peripheral debug outputs
	output        debug_selectVIA,
	output        debug_selectNuBus,
	output        debug_selectSCSI,
	output        debug_selectSCC,
	output        debug_selectIWM,
	output        debug_memoryOverlayOn,
	output [31:0] debug_cpuAddr,
	output [15:0] debug_cpuDataIn,    // Data from CPU to peripherals
	output [15:0] debug_cpuDataOut,   // Data from peripherals to CPU
	output        debug_cpuRW,        // 1=read, 0=write
	output        debug_cpuBusControl,
	output        debug_viaRd,        // VIA read enable (VMA-synchronized)
	output        debug_viaWr,        // VIA write enable (VMA-synchronized)
	output        debug_cpuVMA,       // VMA signal (active low)
	output        debug_selectVIA2,
	output        debug_berr,
	output [31:0] debug_vbr,
	output  [2:0] debug_cpuIPL,

	// Serial terminal interface
	output        serial_txd,       // SCC Channel A TX output (for sim-side RX)
	input         serial_rxd,       // SCC Channel A RX input (from sim-side TX)

	// Machine configuration inputs
	input  [1:0]  cfg_cpuType,      // 00=FX68K, 01/10/11=TG68K variants
	input         cfg_memSize       // 0=1MB, 1=4MB
);

	localparam SCSI_DEVS = 2;

	// Configuration - directly from inputs (Mac II)
	wire      status_mem = cfg_memSize;      // 0=1MB, 1=4MB
	wire [1:0] status_cpu = cfg_cpuType;     // CPU type (must use TG68K 68030 mode)
	// Mac II: 32.5 MHz system clock, CPU at 16 MHz via clock enables
	// status_turbo=1 selects clk16 enables (16 MHz CPU), =0 selects clk8 (8 MHz)
	wire      status_turbo = 1'b1;           // 16 MHz CPU for Mac II
	////////////////////   CLOCKS   ///////////////////

	// Clock generation (clk_sys is 32.5 MHz from testbench, matching FPGA PLL)
	wire clk_mem = clk_sys;  // Use same clock for memory
	wire pll_locked = !reset;

	// Clock enables - generated by addrController_top
	wire clk8_en_p, clk8_en_n;
	wire clk16_en_p, clk16_en_n;
	wire clk8;
	
	// Generate 32MHz clock enable (every cycle at 32MHz base clock)
	reg clk32_en_p, clk32_en_n;
	always @(posedge clk_sys) clk32_en_p <= 1'b1;
	always @(negedge clk_sys) clk32_en_n <= 1'b1;

	// Reset logic
	// NOTE: Do NOT include _cpuReset_o here! The RESET instruction drives
	// reset_n low to reset peripherals, but should NOT reset the CPU itself.
	// IMPORTANT: In simulation, wait for ROM download to complete before releasing reset
	reg n_reset = 0;
	reg n_reset_prev = 0;
	reg dio_download_prev = 0;
	always @(posedge clk_sys) begin
		reg [15:0] rst_cnt;

		if (clk8_en_p) begin
			n_reset_prev <= n_reset;
			dio_download_prev <= dio_download;

			// Debug: track when download completes
			if (dio_download_prev && !dio_download) begin
				$display("SIM: dio_download went LOW - ROM download complete");
			end

			if(~pll_locked || reset || dio_download) begin
				rst_cnt <= '1;
				n_reset <= 0;
			end
			else if(rst_cnt) begin
				rst_cnt <= rst_cnt - 1'd1;
				// Debug: show countdown progress every 0x1000 cycles
				if (rst_cnt[11:0] == 12'h000) begin
					$display("SIM: rst_cnt=%04x n_reset=%b", rst_cnt, n_reset);
				end
			end
			else begin
				n_reset <= 1;
			end

			// Debug: track when n_reset changes
			if (n_reset != n_reset_prev) begin
				$display("SIM: *** n_reset changed to %b *** (rst_cnt=%04x)", n_reset, rst_cnt);
			end
		end
	end

	///////////////////////////////////////////////////

	wire nubus_ce_pixel;
	assign CE_PIXEL  = nubus_ce_pixel;

	// Video Output - Mac II NuBus video system
	// nubus_blank is active-high DE (1 = visible pixels, 0 = blanked)
	// VGA_HB/VGA_VB need active-high blanking (1 = blanked), so invert
	assign VGA_R  = nubus_r;
	assign VGA_G  = nubus_g;
	assign VGA_B  = nubus_b;
	wire VGA_DE = nubus_blank;
	assign VGA_VS = nubus_vsync;
	assign VGA_HS = nubus_hsync;
	assign VGA_HB = ~nubus_blank;
	assign VGA_VB = ~nubus_blank;

	wire [15:0] asc_audio_l, asc_audio_r;
	assign AUDIO_L = asc_audio_l;
	assign AUDIO_R = asc_audio_r;

	// Mac II memory configuration
	localparam configROMSize = 2'b10;  // 256K ROM
	wire [1:0] configRAMSize = 2'b10; // 4MB (00=1MB, 01=2MB, 10=4MB, 11=8MB)

	// Serial Ports — connected to serial terminal in sim_main.cpp
	wire serialOut;              // SCC Channel A TX (driven by SCC)
	wire serialIn = serial_rxd; // SCC Channel A RX (driven by sim)
	wire serialCTS = 1'b0;
	wire serialRTS;
	assign serial_txd = serialOut;

	// NuBus Video system wires
	wire [15:0] nubusDataOut_card;
	wire nubusAck_card;
	wire nubus_irq_n;

	// NuBus arbiter: handles empty-slot bus errors (see nubus_arbiter.sv)
	wire [15:0] nubusDataOut;
	wire nubusAck;
	wire nubus_acked_arb;
	wire nubus_berr;

	nubus_arbiter nubus_arb (
		.clk(clk_sys),
		._cpuAS(_cpuAS),
		.cpuAddr(cpuAddr),
		.selectNuBus(selectNuBus),
		.card_data_out(nubusDataOut_card),
		.card_ack_n(nubusAck_card),
		.data_out(nubusDataOut),
		.ack_n(nubusAck),
		.acked(nubus_acked_arb),
		.berr(nubus_berr)
	);
	wire [7:0] nubus_r, nubus_g, nubus_b;
	wire nubus_hsync, nubus_vsync, nubus_blank;
	wire selectNuBus;

	// interconnects
	// CPU
	wire _cpuReset, _cpuReset_o, _cpuUDS, _cpuLDS, _cpuRW, _cpuAS;
	wire _cpuVMA, _cpuVPA, _cpuDTACK;
	wire E_rising, E_falling;
	wire [2:0] _cpuIPL;
	wire [2:0] cpuFC;
	wire [7:0] cpuAddrHi;
	wire [31:0] cpuAddr;
	wire [15:0] cpuDataOut;

	// RAM/ROM
	wire _romOE;
	wire _ramOE, _ramWE;
	wire _memoryUDS, _memoryLDS;
	wire videoBusControl;
	wire dioBusControl;
	wire cpuBusControl;
	wire [21:0] memoryAddr;
	wire [15:0] memoryDataOut;
	wire memoryLatch;
	wire capslock;
	
	// peripherals
	wire vid_alt, loadPixels, pixelOut, _hblank, _vblank, hsync, vsync;
	wire memoryOverlayOn, selectSCSI, selectSCC, selectIWM, selectVIA, selectVIA2, selectRAM, selectROM, selectSEOverlay, selectASC;
	wire [15:0] dataControllerDataOut;


	// floppy disk image interface
	wire dskReadAckInt;
	wire [21:0] dskReadAddrInt;
	wire dskReadAckExt;
	wire [21:0] dskReadAddrExt;

	// dtack generation in turbo mode
	reg  turbo_dtack_en, cpuBusControl_d;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			turbo_dtack_en <= 0;
		end
		else begin
			cpuBusControl_d <= cpuBusControl;
			if (_cpuAS) turbo_dtack_en <= 0;
			if (!_cpuAS & ((!cpuBusControl_d & cpuBusControl) | (!selectROM & !selectRAM))) turbo_dtack_en <= 1;
		end
	end

	// VPA: assert for FC=7 (autovector), 24-bit VIA space, and 32-bit VIA/VIA2 accesses
	wire viaAccess = selectVIA | selectVIA2;
	assign      _cpuVPA = (cpuFC == 3'b111) ? 1'b0 :
	                      viaAccess ? ~!_cpuAS :
	                      ~(!_cpuAS && cpuAddr[23:21] == 3'b111);
	// DTACK: do not assert for VIA accesses (they use VPA/VMA synchronous handshake)
	assign      _cpuDTACK = selectNuBus ? nubusAck :
	                        viaAccess ? 1'b1 :
	                        (~(!_cpuAS && cpuAddr[23:21] != 3'b111) | (status_turbo & !turbo_dtack_en));

	// Bus error timeout — undecoded addresses trigger bus error after ~8us
	reg [8:0] berr_counter;
	reg berr_out;
	wire nubus_acked = nubus_acked_arb;  // from nubus_arbiter: card or empty-slot responded
	wire any_select = selectRAM | selectROM | selectVIA | selectVIA2 | selectSCC
	                | selectSCSI | selectIWM | selectASC | nubus_acked | selectSEOverlay;
	wire is_cpu_space = (cpuFC == 3'b111);

	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			berr_counter <= 0;
			berr_out <= 0;
		end else begin
			if (_cpuAS) begin
				berr_counter <= 0;
				berr_out <= 0;
			end else if (berr_out) begin
				// Hold BERR until AS deasserts (CPU ends bus cycle)
			end else if (is_cpu_space || any_select)
				berr_counter <= 0;
			else if (berr_counter == 9'd260)  // ~8us at 32.5 MHz sys clock
				begin berr_out <= 1; berr_counter <= 0; end
			else
				berr_counter <= berr_counter + 1'd1;
		end
	end
	// Mac II: 16 MHz CPU (status_turbo=1 selects clk16 enables from 32.5 MHz sys clock)
	wire        cpu_en_p      = status_turbo ? clk16_en_p : clk8_en_p;
	wire        cpu_en_n      = status_turbo ? clk16_en_n : clk8_en_n;
	assign      _cpuReset_o   = tg68_reset_n;
	assign      _cpuRW        = tg68_rw;
	assign      _cpuAS        = tg68_as_n;
	assign      _cpuUDS       = tg68_uds_n;
	assign      _cpuLDS       = tg68_lds_n;
	assign      E_falling     = tg68_E_falling;
	assign      E_rising      = tg68_E_rising;
	assign      _cpuVMA       = tg68_vma_n;
	assign      cpuFC[0]      = tg68_fc0;
	assign      cpuFC[1]      = tg68_fc1;
	assign      cpuFC[2]      = tg68_fc2;
	assign      cpuAddr       = tg68_a;  // Full 32-bit address
	assign      cpuDataOut    = tg68_dout;

	// tg68k wire declarations
	wire        tg68_rw;
	wire        tg68_as_n;
	wire        tg68_uds_n;
	wire        tg68_lds_n;
	wire        tg68_E_rising;
	wire        tg68_E_falling;
	wire        tg68_vma_n;
	wire        tg68_fc0;
	wire        tg68_fc1;
	wire        tg68_fc2;
	wire [15:0] tg68_dout;
	wire [31:0] tg68_a;
	wire        tg68_reset_n;

	tg68k tg68k_inst (
		.clk        ( clk_sys      ),
		.reset      ( !_cpuReset   ),
		.phi1       ( cpu_en_p     ),
		.phi2       ( cpu_en_n     ),
		.cpu        ( 2'b11        ), // 68020 mode (cpu(0) must be 1 for VBR support)

		.dtack_n    ( _cpuDTACK    ),
		.rw_n       ( tg68_rw      ),
		.as_n       ( tg68_as_n    ),
		.uds_n      ( tg68_uds_n   ),
		.lds_n      ( tg68_lds_n   ),
		.fc         ( { tg68_fc2, tg68_fc1, tg68_fc0 } ),
		.reset_n    ( tg68_reset_n ),

		.E          (              ),
		.E_div      ( status_turbo ),
		.E_PosClkEn ( tg68_E_falling ),
		.E_NegClkEn ( tg68_E_rising  ),
		.vma_n      ( tg68_vma_n   ),
		.vpa_n      ( _cpuVPA      ),

		.br_n       ( 1'b1         ),
		.bg_n       (              ),
		.bgack_n    ( 1'b1         ),

		.ipl        ( _cpuIPL      ),
		.berr       ( berr_out     ),
		.cpu_halted (              ),
		.din        ( dataControllerDataOut ),
		.dout       ( tg68_dout    ),
		.addr       ( tg68_a       ),
		.VBR_out    ( debug_vbr    )
	);
	
	// CPU debug - simplified without busstate
	reg [31:0] last_fetch_pc;
	reg [15:0] last_fetch_opcode;
	reg        fetch_valid;
	reg  [2:0] last_fetch_fc;
	reg        prev_as_n;

	// Write capture for vector table watchpoint
	reg        write_valid;
	reg [31:0] write_addr;
	reg [15:0] write_data;

	// Capture VIA read data while AS is still asserted
	reg [15:0] via_rd_data_r;
	always @(posedge clk_sys) begin
		if (!tg68_as_n && selectVIA && tg68_rw)
			via_rd_data_r <= dataControllerDataOut;
	end

	always @(posedge clk_sys) begin
		if (!n_reset) begin
			fetch_valid <= 0;
			write_valid <= 0;
			prev_as_n <= 1;
			last_fetch_pc <= 0;
			last_fetch_opcode <= 0;
			last_fetch_fc <= 0;
		end else begin
			fetch_valid <= 0;
			write_valid <= 0;
			prev_as_n <= tg68_as_n;

			// Capture on AS rising edge (bus cycle complete)
			if (!prev_as_n && tg68_as_n) begin
				if (tg68_rw && (cpuFC == 3'b010 || cpuFC == 3'b110)) begin
					// Only capture instruction fetches (FC=2 supv program, FC=6 user program)
					last_fetch_pc <= tg68_a;
					last_fetch_opcode <= dataControllerDataOut;
					last_fetch_fc <= cpuFC;
					fetch_valid <= 1;
				end else if (!tg68_rw) begin
					// Write cycle - capture for vector watchpoint
					write_addr <= tg68_a;
					write_data <= tg68_dout[15:0];
					write_valid <= 1;
				end
				// Uncomment for VIA bus read debugging:
				// if (tg68_rw && tg68_a[31:20] == 12'h50F)
				//	$display("VIA_BUS_RD_LATE: addr=%h data=%h via_din_r=%h UDS=%b LDS=%b selVIA=%b",
				//		tg68_a, dataControllerDataOut, via_rd_data_r, _cpuUDS, _cpuLDS, selectVIA);
			end
		end
	end

	assign debug_pc = last_fetch_pc;
	assign debug_opcode = last_fetch_opcode;
	assign debug_fetch_valid = fetch_valid;
	assign debug_fc = last_fetch_fc;
	assign debug_write_valid = write_valid;
	assign debug_write_addr = write_addr;
	assign debug_write_data = write_data;
	assign debug_berr = berr_out;

	addrController_top ac0
	(
		.clk(clk_sys),
		.clk8(clk8),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.clk16_en_p(clk16_en_p),
		.clk16_en_n(clk16_en_n),
		.cpuAddr(cpuAddr),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuAS(_cpuAS),
		.turbo(status_turbo),
		.configROMSize(configROMSize),
		.configRAMSize(configRAMSize),
		.memoryAddr(memoryAddr),
		.memoryLatch(memoryLatch),
		._memoryUDS(_memoryUDS),
		._memoryLDS(_memoryLDS),
		._romOE(_romOE),
		._ramOE(_ramOE),
		._ramWE(_ramWE),
		.videoBusControl(videoBusControl),
		.dioBusControl(dioBusControl),
		.cpuBusControl(cpuBusControl),
		.selectSCSI(selectSCSI),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectVIA2(selectVIA2),
		.selectRAM(selectRAM),
		.selectROM(selectROM),
		.selectSEOverlay(selectSEOverlay),
		.selectNuBus(selectNuBus),
		.selectASC(selectASC),
		.hsync(hsync),
		.vsync(vsync),
		._hblank(_hblank),
		._vblank(_vblank),
		.loadPixels(loadPixels),
		.vid_alt(vid_alt),
		.memoryOverlayOn(memoryOverlayOn),

		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt)
	);

	wire [1:0] diskEject;
	wire [1:0] diskMotor, diskAct;

	// NuBus Video Card — Mac II High-Resolution (TFB 2.2 + Bt453)
	// Sim VRAM: simple synchronous RAM standing in for SDRAM
	wire [24:0] sim_vram_addr;
	wire [15:0] sim_vram_dout;
	wire [15:0] sim_vram_din;
	wire        sim_vram_rd;
	wire        sim_vram_wr;
	wire        sim_vram_ready;

	sim_vram #(.ADDR_BITS(19)) sim_vram_inst (
		.clk(clk_sys),
		.reset(!_cpuReset),
		.addr(sim_vram_addr[18:0]),
		.din(sim_vram_dout),
		.dout(sim_vram_din),
		.rd(sim_vram_rd),
		.wr(sim_vram_wr),
		.ready(sim_vram_ready)
	);

	nubus_video_highres nubus_card (
		.clk(clk_sys),
		.reset(!_cpuReset),
		.addr(cpuAddr),
		.data_in(cpuDataOut),
		.data_out(nubusDataOut_card),
		.uds_lds({!_cpuUDS, !_cpuLDS}),
		.rw_n(_cpuRW),
		.select(selectNuBus),
		.ack_n(nubusAck_card),
		.vga_r(nubus_r),
		.vga_g(nubus_g),
		.vga_b(nubus_b),
		.vga_hs(nubus_hsync),
		.vga_vs(nubus_vsync),
		.vga_blank(nubus_blank),
		.vga_clk(),
		.ce_pixel(nubus_ce_pixel),
		.nmrq_n(nubus_irq_n),

		.vram_addr(sim_vram_addr),
		.vram_dout(sim_vram_dout),
		.vram_din(sim_vram_din),
		.vram_rd(sim_vram_rd),
		.vram_wr(sim_vram_wr),
		.vram_ready(sim_vram_ready),

		.overlay_en(1'b0),

		.ioctl_wr(ioctl_wr),
		.ioctl_addr(ioctl_addr),
		.ioctl_data(ioctl_dout),
		.ioctl_download(ioctl_download),
		.ioctl_index(ioctl_index)
	);

	dataController_top #(SCSI_DEVS) dc0
	(
		.clk32(clk_sys),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.E_rising(E_rising),
		.E_falling(E_falling),
		.machineType(1'b1),  // Mac II mode
		.macModel(3'd2),     // Mac II (non-FDHD)
		.configRAMSize(configRAMSize),
		._systemReset(n_reset),
		._cpuReset(_cpuReset),
		._cpuIPL(_cpuIPL),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuVMA(_cpuVMA),
		.selectNuBus(selectNuBus),
		.nubusDataIn(nubusDataOut),
		.nubus_irq_n(nubus_irq_n),
		.cpuDataIn(cpuDataOut),
		.cpuDataOut(dataControllerDataOut),
		.cpuAddrRegHi(cpuAddr[12:9]),
		.cpuAddrRegMid(cpuAddr[6:4]),
		.cpuAddrRegLo(cpuAddr[2:1]),
		.selectSCSI(selectSCSI),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectVIA2(selectVIA2),
		.selectSEOverlay(selectSEOverlay),
		.selectASC(selectASC),
		.cpuAddrASC(cpuAddr[12:0]),
		.cpuBusControl(cpuBusControl),
		.videoBusControl(videoBusControl),
		.memoryDataOut(memoryDataOut),
		.memoryDataIn(ram_do),
		.memoryLatch(memoryLatch),

		.ps2_key(ps2_key),
		.capslock(capslock),
		.ps2_mouse(ps2_mouse),
		.serialIn(serialIn),
		.serialOut(serialOut),
		.serialCTS(serialCTS),
		.serialRTS(serialRTS),

		.timestamp(timestamp),

		._hblank(_hblank),
		._vblank(_vblank),
		.pixelOut(pixelOut),
		.loadPixels(loadPixels),
		.vid_alt(vid_alt),

		.memoryOverlayOn(memoryOverlayOn),

		.ascAudioLeft(asc_audio_l),
		.ascAudioRight(asc_audio_r),

		.insertDisk({dsk_ext_ins, dsk_int_ins}),
		.diskSides({dsk_ext_ds, dsk_int_ds}),
		.diskEject(diskEject),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.diskMotor(diskMotor),
		.diskAct(diskAct),

		.img_mounted(img_mounted),
		.img_size(img_size[40:9]),
		.io_lba(sd_lba),
		.io_rd(sd_rd),
		.io_wr(sd_wr),
		.io_ack(sd_ack),

		.sd_buff_addr(sd_buff_addr),
		.sd_buff_dout(sd_buff_dout),
		.sd_buff_din(sd_buff_din),
		.sd_buff_wr(sd_buff_wr)
	);

	//////////////////////// DOWNLOADING ///////////////////////////

	wire dio_download = ioctl_download;
	wire [23:0] dio_addr = ioctl_addr[24:1];
	wire [7:0] dio_index = ioctl_index;

	// Floppy disk image tracking
	reg dsk_int_ds, dsk_ext_ds;
	reg dsk_int_ss, dsk_ext_ss;
	wire dsk_int_ins = dsk_int_ds || dsk_int_ss;
	wire dsk_ext_ins = dsk_ext_ds || dsk_ext_ss;

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 1) begin
			dsk_int_ds <= (dio_addr == 409600);
			dsk_int_ss <= (dio_addr == 204800);
		end
		if(diskEject[0]) begin
			dsk_int_ds <= 0;
			dsk_int_ss <= 0;
		end
	end

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(old_down && ~dio_download && dio_index == 2) begin
			dsk_ext_ds <= (dio_addr == 409600);
			dsk_ext_ss <= (dio_addr == 204800);
		end
		if(diskEject[1]) begin
			dsk_ext_ds <= 0;
			dsk_ext_ss <= 0;
		end
	end

	reg [20:0] dio_a;
	reg [15:0] dio_data;
	reg        dio_write;
	reg        dio_old_cyc = 0;

	always @(posedge clk_sys) begin
		if(ioctl_wr) begin
			// Don't byte-swap for sim_ram (original swaps for SDRAM byte ordering)
			dio_data <= ioctl_dout;
			// Mac II ROM (boot0.rom, 256K = 128K words) starts at 0x40_0000 in address space
			// In sim_ram, ROM area is at bit[21]=1, so ROM goes to 0x200000+ in sim_ram
			// Floppy disk images use index 1 and 2
			dio_a <= dio_index[1:0] ? {dio_index[1:0], dio_addr[18:0]} :
				{4'b0000, dio_addr[16:0]};  // ROM: 256K = 128K words (17 bits)
			ioctl_wait <= 1;
		end

		dio_old_cyc <= dioBusControl;
		if(~dioBusControl) dio_write <= ioctl_wait;
		if(dio_old_cyc & ~dioBusControl & dio_write) ioctl_wait <= 0;
	end

	////////////////////////// RAM /////////////////////////////////

	// Original download_cycle used dioBusControl handshake (for SDRAM timing)
	// wire download_cycle = dio_download && dioBusControl;

	// For simulation with synchronous RAM, use simplified direct download path
	// This bypasses the multi-cycle handshake latency from dioBusControl
	wire download_cycle = dio_download && ioctl_wr;

	// Combinational version of dio_a for download (avoids register latency)
	// Mac II ROM (boot0.rom, 256K) starts at 0x40_0000 in address space
	// ROM is 256K = 128K words, using dio_addr[16:0] (17 bits)
	// Floppy disk images at higher offsets
	wire [20:0] dio_a_comb = dio_index[1:0] ? {dio_index[1:0], dio_addr[18:0]} :
	                         {4'b0000, dio_addr[16:0]};  // ROM: 256K = 128K words (17 bits)

	// Address mapping for sim_ram:
	// sim_ram uses addr[21:0] for a 4M word (8MB) array
	//
	// For RAM path: {3'b000, dskReadAck, memoryAddr[21:1]}
	//   - This gives addr[21:0] = {dskReadAck, memoryAddr[21:1]}
	//   - Normal RAM (dskReadAck=0): uses 0x000000 - 0x1FFFFF (4MB = 2M words)
	//
	// For ROM path: Need bit 21 = 1 to avoid collision with RAM
	//   - {3'b000, 1'b1, dio_a_comb[20:0]} gives addr[21:0] = {1, dio_a_comb[20:0]} = 0x200000 + dio_a_comb
	wire [24:0] ram_addr = download_cycle ? {3'b000, 1'b1, dio_a_comb[20:0] } :  // ROM at 0x200000+ (bit 21 set)
						   ~_romOE        ?
						   {3'b000, 1'b1, 4'b0000, memoryAddr[17:1]} :  // ROM reads at 0x200000+ (256K ROM) - must be 25 bits!
										  {3'b000, (dskReadAckInt || dskReadAckExt), memoryAddr[21:1]};  // RAM at 0x000000+
	// Use ioctl_dout directly for download (bypass registered dio_data)
	wire [15:0] ram_din  = download_cycle ? ioctl_dout            : memoryDataOut;
	wire  [1:0] ram_ds   = download_cycle ? 2'b11                 : { !_memoryUDS, !_memoryLDS };
	// Use ioctl_wr directly as write enable during download (bypass registered dio_write)
	wire        ram_we   = download_cycle ? 1'b1                  : !_ramWE;
	wire        ram_oe   = download_cycle ? 1'b0                  : (!_ramOE || !_romOE || dskReadAckInt || dskReadAckExt);
	wire [15:0] ram_do_raw;
	wire [15:0] ram_do   = download_cycle ? 16'hffff : (dskReadAckInt || dskReadAckExt) ? extra_rom_data_demux : ram_do_raw;
	wire [15:0] extra_rom_data_demux = memoryAddr[0] ?
						   {ram_do_raw[7:0],ram_do_raw[7:0]}:{ram_do_raw[15:8],ram_do_raw[15:8]};

	sim_ram ram
	(
		.clk            ( clk_sys     ),
		.reset          ( reset       ),
		.din            ( ram_din     ),
		.addr           ( ram_addr    ),
		.ds             ( ram_ds      ),
		.we             ( ram_we      ),
		.oe             ( ram_oe      ),
		.dout           ( ram_do_raw  ),
		.debug_pc       ( last_fetch_pc )
	);

	// RAM debug outputs
	assign debug_ram_addr = ram_addr;
	assign debug_ram_din = ram_din;
	assign debug_ram_dout = ram_do_raw;
	assign debug_ram_we = ram_we;
	assign debug_ram_oe = ram_oe;
	assign debug_ram_ds = ram_ds;
	assign debug_selectRAM = selectRAM;
	assign debug_selectROM = selectROM;

	// Peripheral debug outputs
	assign debug_selectVIA = selectVIA;
	assign debug_selectNuBus = selectNuBus;
	assign debug_selectSCSI = selectSCSI;
	assign debug_selectSCC = selectSCC;
	assign debug_selectIWM = selectIWM;
	assign debug_memoryOverlayOn = memoryOverlayOn;
	assign debug_cpuAddr = cpuAddr;  // Full 32-bit address for Mac II
	assign debug_cpuDataIn = cpuDataOut;  // CPU writes this to peripherals
	assign debug_cpuDataOut = dataControllerDataOut;  // Peripherals send this to CPU
	assign debug_cpuRW = _cpuRW;  // 1=read, 0=write
	assign debug_cpuBusControl = cpuBusControl;
	assign debug_viaRd = (selectVIA || selectVIA2) && !_cpuVMA && _cpuRW;
	assign debug_viaWr = (selectVIA || selectVIA2) && !_cpuVMA && !_cpuRW;
	assign debug_cpuVMA = _cpuVMA;
	assign debug_selectVIA2 = selectVIA2;
	assign debug_cpuIPL = _cpuIPL;

endmodule
